### ISSUE TITLE
Setup storybook addons

### ISSUE THREAD

**Issue by conrad-vanl** [NewSpring/Apollos#10]
Lets take a peek at the available storybook addons and make sure we setup those that we want to use:
https://storybook.js.org/addons/addon-gallery

Might be relevant to touch base with Drew or Nick to see what addons they see most relevant

Candidates:
- Links: link stories together
- Knobs: allow you to edit props from the Storybook UI
- Info: show docs / other info in Storybook UI (could be how we document our code)
   - Or the community addon "readme"
- Storyshots: automatic jest-snapshots for all stories
- Story-router: allows you to integrate react-router components in stories
- JSX preview: shows the JSX code used to render the story
- Apollo: for mocking apollo data

**Comment by burkeshartsis** [comment]
I looked into and tried a few documentation based addons and none of them completely work with our setup on RN and Web. Below are some notes for when someone circles back on this.

- [Info](https://github.com/storybooks/storybook/tree/master/addons/info): This will remain unusable until [this](https://github.com/storybooks/storybook/pull/1501) PR is merged.
- [Props](https://www.npmjs.com/package/storybook-addon-props): This looked promising and might be solvable but my tests died [here](https://github.com/storybooks/storybook/issues/1192). The developer of this PR also said it will be deprecated when the Info PR above is merged.
- [Readme](https://github.com/tuchk4/storybook-readme): Should work but would require increased manual documentation.
- [Notes](https://github.com/storybooks/storybook/tree/master/addons/notes): See Readme above.

**Comment by burkeshartsis** [comment]
Not sure about this addon's  compatibility but looks promising. https://github.com/mthuret/storybook-addon-specifications

**Comment by conrad-vanl** [comment]
> Props: This looked promising and might be solvable but my tests died here. The developer of this PR also said it will be deprecated when the Info PR above is merged.

Burke said: I think we can get this to work now, due to babel config change.

**Comment by burkeshartsis** [comment]
[Storyshots](https://github.com/storybooks/storybook/tree/master/addons/storyshots) would be nice to have too. Currently it outputs all the snapshots into a single file (gross) the maintainers have a fix in the next release (already merged into the release branch) that addresses this by storying the snapshot next to the test. You can track that issue [here](https://github.com/storybooks/storybook/issues/887).
