### ISSUE TITLE
Style Media Card Component

### ISSUE THREAD

**Issue by conrad-vanl** [NewSpring/Apollos#114]
Take `MediaCard` component from #40 and flush out styles and taps:

- [ ] Tapping heart "likes" the content
- [ ] Tapping the card navigates to a new route

## Acceptance Criteria

- [ ] It should have a heart icon
- [ ] It should have a title
- [ ] It should have a subtitle and icon
- [ ] It should have an image
- [ ] It should support having the image fill the entire media panel
- [ ] It should have a fixed height

## Context
Holtzman/imports/components/@primitives/UI/cards

## UI Screenshot or Wireframe (optional)
![img_f91801c61601-1](https://user-images.githubusercontent.com/2302110/32061717-3c64de24-ba27-11e7-9d50-275dc498fba8.jpeg)
![img_99655220222c-1](https://user-images.githubusercontent.com/2302110/32061718-3c7dbca0-ba27-11e7-83dc-43d1325686c1.jpeg)

**Comment by burkeshartsis** [comment]
Fixed by #133
