### ISSUE TITLE
Setup CI service

### ISSUE THREAD

**Issue by conrad-vanl** [NewSpring/Apollos#12]
## Acceptance Criteria

- [ ] Hookup TravisCI to repo
- [ ] Setup automatic builds/testing on master and every PR
- [ ] Make master a "protected" branch, setup PRs to require peer review and passing tests before merge

**Comment by Lepozepo** [comment]
@conrad-vanl I don't have access to set up travis on behalf of new spring, do you? If not, who can we get that from?

**Comment by conrad-vanl** [comment]
@delianides or @richarddubay How should we go about setting up TravisCI? It looks like we can request access:

![image](https://user-images.githubusercontent.com/103927/31909836-01e90ce8-b801-11e7-8434-0cbae4c5ea89.png)

Is this the proper route to take?

**Comment by richarddubay** [comment]
Hey @conrad-vanl, I think @meredithrouse took care of this yesterday, right?

**Comment by conrad-vanl** [comment]
Confirmed. Thanks!
