### ISSUE TITLE
Content Siblings

### ISSUE THREAD

**Issue by conrad-vanl** [NewSpring/Apollos#157]
related to #154 

## Acceptance Criteria

- [x] horizontal card list of study entries inside of a study (devotional) that you see when you go to a devotional.
- [x] horizontal card list of sermons inside of a series that you see when you go to a sermon
- [ ] auto-scroll to the next entry

**Comment by burkeshartsis** [comment]
Closed by #208

**Comment by conrad-vanl** [comment]
@burkeshartsis not sure if this is actually closed. Siblings vs children. I think what’s in master is just series to sermon or study to study entry navigation. On the current app, you can also navigate to sibling study entries from a study entry, or sibling sermons from the same series from within a sermon

**Comment by burkeshartsis** [comment]
@conrad-vanl ahhh boo! I'm sorry. It's basically the same navigation just in a different place. I'll open a PR to address it this week!
