### ISSUE TITLE
Giving: subnav

### ISSUE THREAD

**Issue by conrad-vanl** [NewSpring/Apollos#163]
## Acceptance Criteria

- [ ] Tapping on "Giving" in navigation opens "Giving" Subnav

**Comment by IsaacHardy** [comment]
@burkeshartsis @conrad-vanl Is this something we still want to do? My understanding was that we were getting rid of the sub-nav within Apollos.

**Comment by burkeshartsis** [comment]
If there is consensus on your end that you are ok with eliminating it I'm happy to close this and someone can reopen it at a later date if need be. I'm of the opinion that it doesn't add anything to the user experience so we're not loosing anything that will affect the user.
