### ISSUE TITLE
Integrate Raygun or some monitoring service that is cheaper than New Relic

### ISSUE THREAD

**Issue by jbaxleyiii** [NewSpring/Apollos#195]
This is for Heighliner. @delianides let me know if you need help with this.

**Comment by delianides** [comment]
Not for launch right?

Drew Delianides
Web Developer, NewSpring Church
847-345-5404
http://newspring.cc




On Wed, Feb 24, 2016 at 7:30 PM -0800, "James Baxley" <notifications@github.com> wrote:












This is for Heighliner. @delianides let me know if you need help with this.

**Comment by jbaxleyiii** [comment]
@delianides I've set this up for heighliner and for apollos. It doesn't give us as much performance monitoring as new relic does for server timelines, however it is WAY better for client timelines. I'm not sure Raygun can 100% replace new relic but I have a 30 day trial so we can evaluate it

**Comment by jbaxleyiii** [comment]
Lets see how it does for the next few days and evaluate it before closing this

**Comment by jbaxleyiii** [comment]
we ended up paying for new relic
