### ISSUE TITLE
Prompt user to ensure they want to cancel a schedule

### ISSUE THREAD

**Issue by jbaxleyiii** [NewSpring/Apollos#197]
@samclaridge we will need copy for this action. I think having it happen in a modal is probably the easiest solution for now?

**Comment by jbaxleyiii** [comment]
@jonhorton do you have copy you want in this modal?

**Comment by jbaxleyiii** [comment]
<img width="364" alt="screenshot 2016-02-26 10 46 37" src="https://cloud.githubusercontent.com/assets/4967600/13357099/cd847616-dc76-11e5-9207-67f24e297020.png">

**Comment by jonhorton** [comment]
Body: Want to stop your scheduled gift? You can always create another when you're ready. 

Button: Cancel Schedule

@jbaxleyiii

**Comment by jbaxleyiii** [comment]
@jonhorton updated in PR!
