### ISSUE TITLE
Add like functionality to groups

### ISSUE THREAD

**Issue by Lepozepo** [NewSpring/Apollos#205]
## Acceptance Criteria

- [ ] It should allow liking groups
- [x] It should read whether a group is liked from graphql
- [x] It should write group likes through `toggleLike`

**Comment by conrad-vanl** [comment]
If you can just do this part:

>  It should read whether a group is liked from graphql

by adding an `isLiked` prop to groups on Heighliner, and then make sure groups are returned in the `userLikes` query, I can do the frontend changes.

**Comment by Lepozepo** [comment]
Server PR is [here](https://github.com/NewSpring/Heighliner/pull/353)

**Comment by Lepozepo** [comment]
@conrad-vanl I made a few modifications to apollo just to get things ready [here](https://github.com/NewSpring/Apollos/pull/280). I'll finish patching the `optimisticResponse` on Monday morning but you should be able to work in the UI part already ^_^
