### ISSUE TITLE
EmbededVideo player orientation change

### ISSUE THREAD

**Issue by burkeshartsis** [NewSpring/Apollos#221]
Currently when you tap on a video to play and rotate the device the video image is black. If we are still using Ooyala there maybe a solution [here](http://apidocs.ooyala.com/player_v4_js/OO.EVENTS.html#event_SIZE_CHANGED).

## Acceptance Criteria

- [x] The video should play correctly after device orientation change.
- [x] Bonus points if it continues playing where it left off 😉 
- [ ] A truck load of bonus points if it uses the native video player 🚚 💯

**Comment by IsaacHardy** [comment]
Signs are pointing to us switching to Wistia.

**Comment by conrad-vanl** [comment]
Fixed in #262 for iOS.
full-screening from a webview is currently broken in react-native

We should re-address this once the switch to Wistia is underway.
