### ISSUE TITLE
Series/Study Nav broken with long titles

### ISSUE THREAD

**Issue by burkeshartsis** [NewSpring/Apollos#234]
## Acceptance Criteria

- [ ] Long titles should truncate and not affect header navigation arrow.

## Context

Given a long title for a Series/Study/etc the back arrow navigation in the header is pushed off the screen.

#### iOS
![simulator screen shot - iphone x - 2018-01-22 at 11 18 28](https://user-images.githubusercontent.com/2053547/35231355-8a46a364-ff66-11e7-8e17-5d1ee1b25850.png)

**Comment by conrad-vanl** [comment]
#272 adds in a `truncate` package
