### ISSUE TITLE
Giving UI

### ISSUE THREAD

**Issue by IsaacHardy** [NewSpring/Apollos#248]
## Acceptance Criteria

- [x] ANDROID: Giving input should not cut off placeholder `$0.00` from the top. (1)
- [x] ANDROID: Certain inputs on the billing address view should not be hidden when using the keyboard. (2)
- [x] ANDROID: The text size of the fund input should look more consistent
- [x] Title of third view should be "Payment Details" and not "Billing Address" a second time.
- [x] After giving, the main nav should not be missing. (Had to click back 7-8 times to get back to a screen with the main nav)

## Context

Given [CONTEXT] when [ACTION] then [RESULT]

#### 1
![screenshot_20180123-094733](https://user-images.githubusercontent.com/10745699/35408349-bfaee304-01dc-11e8-99ee-5274a819260b.png)

#### 2
![screenshot_20180123-094831](https://user-images.githubusercontent.com/10745699/35408435-160f9a72-01dd-11e8-99aa-ae350443e212.png)

**Comment by burkeshartsis** [comment]
For clarity, there is no way to improve the current fund selector on android to look better than we have in #297. It's a limitation of RN Android.
