### ISSUE TITLE
Account for utility bar on Android

### ISSUE THREAD

**Issue by IsaacHardy** [NewSpring/Apollos#249]
## Acceptance Criteria

- [ ] The header bar should account for the utility bar on Android. Some text and back button are obscured as a result.

## UI Screenshot or Wireframe (optional)
![screenshot_20180125-145004](https://user-images.githubusercontent.com/10745699/35409138-53d37606-01df-11e8-998e-7e673e3f392c.png)

**Comment by burkeshartsis** [comment]
Good catch! I just documented this as well in #238

**Comment by IsaacHardy** [comment]
Awesome! I will close this PR then in favor of yours.
