### ISSUE TITLE
Global nav not rendering after error

### ISSUE THREAD

**Issue by samclaridge** [NewSpring/Apollos#249]
#Steps To Reproduce
After receiving duplicate transaction error, closed out the modal but the global nav never returned.

https://www.dropbox.com/s/qn9kacibtzcu6wa/Screenshot%202016-02-28%2012.49.24.png?dl=0

**Comment by johnthepink** [comment]
@samclaridge can you still replicate this using the latest from all masters? i just went through 5 duplicate transaction errors without seeing it

**Comment by samclaridge** [comment]
I can’t see it now either, looks like it’s fixed

Samuel Claridge

— Sent from
https://polymail.io/

On Mon, Feb 29, 2016 at 5:26 PM John Pinkerton

<
mailto:John Pinkerton <notifications@github.com>
> wrote:

https://github.com/samclaridge
can you still replicate this using the latest from all masters? i just went through 5 duplicate transaction errors without seeing it
