### ISSUE TITLE
Video playback in web

### ISSUE THREAD

**Issue by IsaacHardy** [NewSpring/Apollos#258]
## Acceptance Criteria

- [ ] Video playback in webview should actually play the video without receiving a network error.

## UI Screenshot or Wireframe (optional)

![screen shot 2018-01-29 at 9 35 51 am](https://user-images.githubusercontent.com/10745699/35515718-e32a356a-04d7-11e8-8187-b5bbb7e666bf.png)

**Comment by conrad-vanl** [comment]
This has to do with the ooyala player trying to load insecure links on https. I'm not sure why it happens.

However, the views on web that point to screens with a web player I believe are going to be disabled.
