### ISSUE TITLE
Login sometimes locks up

### ISSUE THREAD

**Issue by jbaxleyiii** [NewSpring/Apollos#263]
getting can't call componentWillUnmount of null

**Comment by johnthepink** [comment]
can't duplicate. maybe staff account issue?

**Comment by johnthepink** [comment]
@jbaxleyiii staff account is working fine for me too

![](http://2.bp.blogspot.com/-lo-6EaErBDQ/VT2EFiimvnI/AAAAAAAALtg/YtYaZerZ8Mo/s1600/pepe-the-frog-meme-8.png)

**Comment by jbaxleyiii** [comment]
@johnthepink I can't duplicate in the newer build. Will keep this issue open for another day just to make sure

**Comment by jbaxleyiii** [comment]
@johnthepink found the source. The refactoring of the Error template was missed here.  Fixed in #292
