### ISSUE TITLE
Sections external links

### ISSUE THREAD

**Issue by johnthepink** [NewSpring/Apollos#266]
Not redirecting correctly some times.

https://newspring.cc/bible is becoming https://my.newspring.cc/bible and then going nowhere

**Comment by jonhorton** [comment]
Confirmed this happens to me with every external section link I tested!

**Comment by jbaxleyiii** [comment]
https://github.com/NewSpring/Apollos/blob/master/core/pages/index.js#L14-L36 is the supporting method. We need to fix SSR + cloudfront support to turn it back on

**Comment by johnthepink** [comment]
Fixed by #313
