### ISSUE TITLE
complete account

### ISSUE THREAD

**Issue by johnthepink** [NewSpring/Apollos#277]
After creating a new account, then logging out, then logging back in I saw this screen:

![screenshot 2016-02-29 16 55 28](https://cloud.githubusercontent.com/assets/816517/13410371/6508e39c-df05-11e5-9026-cc8d843d83f1.png)

"Complete Account" button does not go anywhere. Also, marketing text

**Comment by jbaxleyiii** [comment]
cc @johnthepink

**Comment by jbaxleyiii** [comment]
@johnthepink that should be a link to `/profile/settings/personal-details`

**Comment by jbaxleyiii** [comment]
Fixed in #340
