### ISSUE TITLE
Prefilled Zip of billing address shows validation error

### ISSUE THREAD

**Issue by jonhorton** [NewSpring/Apollos#285]
On step 2 of the schedule payment process, all of my data is filled in, however the Zip field is red with a "Please enter your zip" error. Zip reads 29621-3941.

I'm still able to click next and proceed.

Also, clicking into the zip field removes the validation error.

**Comment by jbaxleyiii** [comment]
@johnthepink this is related to the 5 character limit, we will need to trim the prefill to 5
