### ISSUE TITLE
Cancel Button

### ISSUE THREAD

**Issue by johnthepink** [NewSpring/Apollos#288]
@samclaridge here's a good one for you

![screenshot 2016-02-29 20 53 03](https://cloud.githubusercontent.com/assets/816517/13415208/f8753ad8-df26-11e5-8b48-d59bc4e9700e.png)

**Comment by jbaxleyiii** [comment]
@samclaridge the class applied is `btn--alert`

**Comment by samclaridge** [comment]
@jbaxleyiii Created pull request with update to junction which should fix this.

**Comment by jbaxleyiii** [comment]
fixed in https://github.com/NewSpring/junction-framework/pull/22
