### ISSUE TITLE
Group Finder Contact Button Does Not Use In-App Browser

### ISSUE THREAD

**Issue by briankalwat** [NewSpring/Apollos#301]
## Acceptance Criteria

- [ ] Tapping the `Contact` button on a group page should open the Rock Group Contact form using the in-app browser vs. switching to a separate browser app.

## Context

Tapping the `Contact` button on a group page currently opens the Rock Group Contact form using a separate browser app.

**Comment by conrad-vanl** [comment]
Should probably do a quick `grep` on everywhere we use `Linking.openURL` to see what else we could/should be showing in-app browser.
