### ISSUE TITLE
Profile image doesn't update

### ISSUE THREAD

**Issue by jonhorton** [NewSpring/Apollos#303]
When attempting to replace a profile image on desktop, I get the following error:
Failed to load resource: the server responded with a status of 415 (Unsupported Media Type)
https://beta-rock.newspring.cc/api/BinaryFiles/Upload?binaryFileTypeId=5

I'm uploading a standard jpg that I use for all profile images.

**Comment by jbaxleyiii** [comment]
This is because of the rollback to beta. Will be back working as soon as we update
