### ISSUE TITLE
Topic Toggle Switches in Profile Section Don't Visually Match Their State

### ISSUE THREAD

**Issue by briankalwat** [NewSpring/Apollos#303]
## Acceptance Criteria

- [ ] Topic toggles in the `Profile` section should be a correct visual representation of their current state (enabled/disabled).

## Context

While viewing the `Topics` tab of the `Profile` section, tapping a toggle to disable a topic from the home feed causes the toggle to animate and then snap back to the enabled position. I verified by going to the home feed and pulling to refresh that it does, in fact, filter the content. It appears that the toggles are not visually matching their state.

**Comment by conrad-vanl** [comment]
Able to reproduce on latest build. Not sure when this issue cropped up. Thanks!
