### ISSUE TITLE
New Schedule button in Giving Dashboard not linking to correct tab.

### ISSUE THREAD

**Issue by cdanwards** [NewSpring/Apollos#304]
## Acceptance Criteria

- [x] When in the Dashboard tab of My Giving, selecting New Schedule should direct to Give Now tab with the schedule this contribution preselected.

## Context

Currently when you select the New Schedule button on the Dashboard tab of My Giving, it takes you to the history tab of my giving.

**Comment by burkeshartsis** [comment]
fixed in #341 but due to technical limitations at the time this works but does not flip the "Schedule Contribution" toggle. We'll circle back on the last part of this.
