### ISSUE TITLE
After a successful schedule transfer the user isn't redirected

### ISSUE THREAD

**Issue by jonhorton** [NewSpring/Apollos#304]
After receiving a Success! modal when transferring a schedule, I'm not redirected anywhere. 

The URL stays /give/schedules/recover, but the screen is white.

https://www.dropbox.com/s/r5ph7bm6oymiu5t/Screenshot%202016-03-01%2020.06.42.png?dl=0

**Comment by jbaxleyiii** [comment]
@jonhorton my plan was to create a default state or /give/schedules/recover. Would you rather they be taken back to /give/schedules?

**Comment by jbaxleyiii** [comment]
see https://github.com/NewSpring/Apollos/issues/298

**Comment by jonhorton** [comment]
Would the default state have some text saying that there were no schedules
to transfer?

If so, I like that idea. Would be a way to have some friendly text.

On Tuesday, March 1, 2016, James Baxley <notifications@github.com> wrote:

> see #298 <https://github.com/NewSpring/Apollos/issues/298>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NewSpring/Apollos/issues/304#issuecomment-191005146>.
>


-- 
Jon Horton
Central Web Director
NewSpring Church
www.newspring.cc
Office: 864.965.9518
Cell: 919.218.6655

**Comment by jbaxleyiii** [comment]
@jonhorton yep!
