### ISSUE TITLE
Button hover state on are you sure? modal is off

### ISSUE THREAD

**Issue by jonhorton** [NewSpring/Apollos#305]
After clicking stop gift (and one other similar screen that I can't remember), the hover state of the button is green instead of red like the button outline.

Screenshot: https://www.dropbox.com/s/qjbfmrm7rxga4ct/Screenshot%202016-03-01%2020.33.18.png?dl=0

**Comment by jbaxleyiii** [comment]
Closing as its a dup of https://github.com/NewSpring/Apollos/issues/288

**Comment by jonhorton** [comment]
@jbaxleyiii I swear I search for duplicates and never see them!
