### ISSUE TITLE
Links flash white on ios when thumbing/scrolling through app.

### ISSUE THREAD

**Issue by cdanwards** [NewSpring/Apollos#306]
## Acceptance Criteria

- [ ] Upon scrolling in app, when touching different sections(links) default white "flash" should not occur.

## Context

Currently, when you thumb through the app on ios, anytime that you touch a link, the whole element flashes white.

**Comment by IsaacHardy** [comment]
We noticed that this issue is absent on an Android Alpha build through the Play store.

**Comment by conrad-vanl** [comment]
Ahhhh now I understand this issue. Yes, we are utilizing React Native's [`TouchableOpacity`](https://facebook.github.io/react-native/docs/touchableopacity.html) native feedback mechanism on most touchables. 

We can either turn down the affect, or not use native feedback at all. Thoughts? @burkeshartsis any other ideas?

In an ideal world, I'd like to see a scale effect applied to cards when you tap on them in iOS, similar to what you see in the new app store, but that's something we could do down the road.

**Comment by burkeshartsis** [comment]
So from a UX perspective some kind of tap feedback is good. It's reassuring for the user and provides a consistent response to user tap interaction app wide. This is especially useful when tappable objects don't have any other discernible CTA. I could see how `TouchableOpacity` might be a bit much and would agree with @conrad-vanl that a slight scale effect would be great. Each native platform has it's own UX feedback pattern (Android has a ripple effect with an optional haptic vibration). My recommendation would be to not remove/change `TouchableOpacity` unless we have a suitable replacement for it.

**Comment by conrad-vanl** [comment]
I think my "easy win" suggestion was just to turn down the affect of the opacity a bit? I'd agree it's a little much now and distracting

**Comment by IsaacHardy** [comment]
@conrad-vanl @burkeshartsis FWIW, We have a build on alpha in the Play Store that @FrankGrand has used, and there seems to be zero touch response. 

I agree that there needs to be some type of feedback and scaling the current touch response is a good start.

**Comment by conrad-vanl** [comment]
@IsaacHardy yep, android is supposed to be using it's native touch response, which shows the material design wave animation. It's either set to white, and white on white === no response, or it's showing the wave under the card instead of on top of it.

Either way, touch responses on android react native, like most things android + react native, are a bit behind and more inconsistent. We can only hope to make it better over time :) (and, fwiw, although low priority, I believe this is something @burkeshartsis wanted to look at IRC)

**Comment by conrad-vanl** [comment]
Might also be able to improve with this prop: https://facebook.github.io/react-native/docs/touchablewithoutfeedback.html#delaypressin
