### ISSUE TITLE
Splash screen background image is not sized correctly.

### ISSUE THREAD

**Issue by cdanwards** [NewSpring/Apollos#307]
## Acceptance Criteria

- [ ] Upon initial load of app, the splash screen background image should fit to the screen.

## Context

Currently, the splash screen image is oversized.

**Comment by cdanwards** [comment]
The WatchLive play image is also not sized correctly.

**Comment by conrad-vanl** [comment]
@IsaacHardy any ideas on the splash screen?

RE: The watch live play image, I'll file a separate issue for that #310

**Comment by IsaacHardy** [comment]
@conrad-vanl There aren't many options for changing the size of the splash screen using the expo build tools. (https://docs.expo.io/versions/latest/guides/configuration.html#splash)

With cordova, you have multiple image options for splash screens. Even vertical/horizontal options. We might have to look at the image itself if we want it to fit the screen correctly for iPhone X. Maybe the dimensions need to be made specifically for X and will adapt for the older iPhones.

**Comment by conrad-vanl** [comment]
On my iPhone X, here is what I see:

![image](https://user-images.githubusercontent.com/103927/36104626-2701777a-0fd8-11e8-9eae-c8a7e6d99cc0.png)

So we might need clarification on what he means by not sized correctly. It appears to be lower resolution, so maybe just uploading a higher-res splash image would be suitable.

**Comment by conrad-vanl** [comment]
Assigning to @IsaacHardy so he can confirm acceptance criteria and hopefully provide the correct art asset.

**Comment by IsaacHardy** [comment]
Looking at that image, it seems the vertical spacing is correct, but the sides are cutting off some of the image. I'll double check the acceptance criteria, but if I was a betting man I'd say it has to do with the sides of that image.

**Comment by conrad-vanl** [comment]
Ah....good catch. Potentially we just need to generate an image that has more spacing / breathing room around it knowing that each device is going to crop it differently.

**Comment by conrad-vanl** [comment]
(and, fwiw, the lower resolution of the image does stand out on an iphone x screen, so if we need to generate a new image, generating it at higher resolution would be nice too)

**Comment by IsaacHardy** [comment]
@conrad-vanl I'll check to see what options we have for splash screen images in Holtzman and go from there. Worst case (or best case depending on how you view it) I'll ask our creative team to come up with an acceptable images for all devices.

**Comment by conrad-vanl** [comment]
@IsaacHardy this issue just received priority. Were you able to look into this any further?

**Comment by IsaacHardy** [comment]
@conrad-vanl It is one of my todos for today. The little research I have done has me thinking our options are not as prevalent as they were with Holtzman.
