### ISSUE TITLE
Music Player disrupting Top Nav bar for some sections

### ISSUE THREAD

**Issue by cdanwards** [NewSpring/Apollos#308]
## Acceptance Criteria

- [ ] While playing music, I should be able to navigate back to previous pages using the top nav bar.

## Context

Currently, when music is playing and you try to return to previous pages in sections like devotionals, the button does not work and can create a skewed screen.

![img_6451](https://user-images.githubusercontent.com/8878532/36079403-5d2cd610-0f50-11e8-952a-eabab263664d.PNG)

**Comment by conrad-vanl** [comment]
Related to #234 @burkeshartsis

**Comment by conrad-vanl** [comment]
Confirmed duplicate of #234 and not related to music playing. Closing.
