### ISSUE TITLE
Closing of music player

### ISSUE THREAD

**Issue by conrad-vanl** [NewSpring/Apollos#312]
## Acceptance Criteria

- [ ] can't quit song from bottom of screen when navigating in the app (it does allow you to pause)

@IsaacHardy / @FrankGrand this was reported by Michael. I don't believe this is possible in the current app either? but ideas on how best to implement it? Simple might be to put like a X second timeout that if you stop playing music, after so many seconds, the player closes.

**Comment by FrankGrand** [comment]
@conrad-vanl This is current functionality.  You swipe right on the music player banner on bottom and it stops the audio.

**Comment by conrad-vanl** [comment]
Woah. I don't think I would've ever figured that out. Ok.

**Comment by IsaacHardy** [comment]
@conrad-vanl This is our fault for not communicating this to you guys sooner. I do agree that it is functionality that isn't exactly intuitive. 

I'm going to relabel this PR to a bug for now.

**Comment by burkeshartsis** [comment]
Let me think on it. It's struck me before as being not quite right UX wise.

**Comment by IsaacHardy** [comment]
@conrad-vanl @burkeshartsis We will need this functionality to work for sermon audio. I would assume the sermon audio and audio playback for music is using the same component, but I just wanted to communicate this anyways.

**Comment by burkeshartsis** [comment]
Yup! Planning to work on it this week.
