### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by conrad-vanl** [NewSpring/Apollos#318]
## Ideas

- High-level design patterns
- Folder structure
- Future plans / intentions behind certain decisions (ie...folder structure, theming, etc)
- Breakdown of technically complex features - ie: HTML rendering, theming
- Idiosyncrasies between iOS / Android
  - Such as keyboard and inputs
  - Font rendering (should be listed but link to separate documentation)
- Custom fonts (this is big enough to have it's own documentation)
- Storybook (what, why, how)
- Media Player

**Comment by conrad-vanl** [comment]
@IsaacHardy starting this running list to figure out points that we want to go back and add color / documentation around. As you dig through the project, feel free to throw out specific thoughts or ideas!

**Comment by burkeshartsis** [comment]
I added a few things to the list above for fonts and storybook.

**Comment by IsaacHardy** [comment]
@conrad-vanl @burkeshartsis One our my team's plan for the next few weeks to begin development on our 2017 Annual Report. I was wondering when we might be able to see some of this documentation to help guide us through this initial development.

**Comment by conrad-vanl** [comment]
@IsaacHardy this was added to sprint...what do we feel are the right next steps for this for the sprint? Is this more of an Apollos Project task or a short-term Newspring task?

**Comment by IsaacHardy** [comment]
This is a short-term NewSpring task. Let's table this until we have more information regarding the new plans being made today.
