### ISSUE TITLE
Triple Scroll Bar Visible on Profile Settings

### ISSUE THREAD

**Issue by briankalwat** [NewSpring/Apollos#322]
The settings modal within profile shows three individual scroll bars, even when they are not necessary. This is coming from the `scrollable` class that is included on the `panel__item-left` element and it's first child element. Removing the `scrollable` class (or changing `overflow-y` to `auto` instead of `scroll`) from these two elements fixes the issue (in this context).

![image](https://cloud.githubusercontent.com/assets/2465823/13482893/e2e34b40-e0bd-11e5-898a-1b814ca83777.png)

![image](https://cloud.githubusercontent.com/assets/2465823/13482589/106e064c-e0bc-11e5-887e-6fac3393be02.png)

**Comment by johnthepink** [comment]
Fixed in #321
