### ISSUE TITLE
URL Structure for Liked & Popular Content is Incorrect

### ISSUE THREAD

**Issue by briankalwat** [NewSpring/Apollos#323]
This is happening for content under `Profile > Likes` AND `Discover > Popular Content`.

Looks like it's currently appending the entry id after the channel url, should be `channel_url/url_title`

![image](https://cloud.githubusercontent.com/assets/2465823/13482628/62de635e-e0bc-11e5-8944-50ff0c77b03f.png)

**Comment by johnthepink** [comment]
We actually removed these in #321 as the app content isn't loaded in my.newspring at this time.
