### ISSUE TITLE
Vertical Alignment of Content Type Icon & Text Looks Weird

### ISSUE THREAD

**Issue by briankalwat** [NewSpring/Apollos#324]
This might be just preference, but I think the icon & text of the content type meta data would look better vertically aligned from the middle rather than the baseline. Just my two cents!

![image](https://cloud.githubusercontent.com/assets/2465823/13482771/fc5f4778-e0bc-11e5-8403-2329c7fbe660.png)

![image](https://cloud.githubusercontent.com/assets/2465823/13482773/01b5861a-e0bd-11e5-8258-325ff5a8ca0b.png)

**Comment by johnthepink** [comment]
@briankalwat same as the other issues. We actually won't be using this on give right now. The styles will be updated when we add them in. Thanks!
