### ISSUE TITLE
Extra Scroll Bar Visible for Likes & Following Profile Sections

### ISSUE THREAD

**Issue by briankalwat** [NewSpring/Apollos#325]
There is a scroll bar for the external container, and then another on `panel__item-left` (coming from the `scrollable` class on that element). Removing the `scrollable` class (or changing `overflow-y` to `auto` instead of `scroll`) eliminates the issue (at least in this context).

![image](https://cloud.githubusercontent.com/assets/2465823/13482840/7652ba74-e0bd-11e5-80a1-e14dc481b56b.png)

![image](https://cloud.githubusercontent.com/assets/2465823/13482792/27780b7a-e0bd-11e5-8371-708f65909579.png)

**Comment by johnthepink** [comment]
Thanks @briankalwat! Fixed by #321
