### ISSUE TITLE
Giving flow integration testing

### ISSUE THREAD

**Issue by conrad-vanl** [NewSpring/Apollos#326]
1. using saved credit card
2. using saved bank account
3. using new credit card
4. using new bank account
5. trying to use an expired card
6. other invalidators

**Comment by conrad-vanl** [comment]
Also, consider these enhancements:

1. Styles of the "Secure Web Checkout" view and flow
2. Styles of `CashAmountIndicator` at size=5
3. Success/Failure text centering
4. Consider extracting `TinyButton` to ui
5. Consider extracting `Row` to ui

**Comment by conrad-vanl** [comment]
Thinking through more flows to test:

1. Setting up a giving schedule and that schedule having a denied transaction down the road
2. An expiring card in a giving schedule
3. Is it possible for a transaction to go into a bad state after it initially succeeded?
4. Updating an expired card?

@IsaacHardy @FrankGrand thinking through the scope of both what we need to test in manual QA, but also starting to think through testing flows for integration tests. Thoughts? Please follow up with additional test cases as you think of them.

**Comment by burkeshartsis** [comment]
Moving style related bugs into separate issues.

**Comment by burkeshartsis** [comment]
From my conversation with @Lepozepo:

### Checkout Flows
- BankAccount Guest
- BankAccount User no saved payment and will save payment method
- BankAccount User no saved payment and will not save payment method
- BankAccount User has saved payment method
- BankAccount User has saved payment method and will change saved payment method and save payment method
- **Hight complexity**: BankAccount User has saved payment method and will change saved payment method and not save payment method
- CreditCard Guest
- CreditCard User no saved payment and will save payment method
- CreditCard User no saved payment and will not save payment method
- CreditCard User has saved payment method
- CreditCard User has saved payment method and will change saved payment method and save payment method
- **Hight complexity**: CreditCard User has saved payment method and will change saved payment method and not save payment method
### Saved Payment Methods
- BankAccount User saves payment method
- CreditCard User saves payment method
