### ISSUE TITLE
Content feeds rendering odd number

### ISSUE THREAD

**Issue by burkeshartsis** [NewSpring/Apollos#330]
## Acceptance Criteria

- [ ] Content feeds (cards) should render 10.
- [ ] On web content feeds should wrap evenly when in two columns.

## Context

Currently content feeds render 11 items and on web it creates a weird wrap (odd number of items). It's also just one more than we want so...

## UI Screenshot or Wireframe (optional)
<img width="1680" alt="feeds render 11" src="https://user-images.githubusercontent.com/2053547/36166962-3357bef4-10c2-11e8-9d7d-2f6d7713d2e6.png">

**Comment by IsaacHardy** [comment]
Completely irrelevant, but I do not like the look of this home view at all. In a perfect world, a redesign to smaller looking blocks would feel much more accessible. Maybe a size similar to Holtzman's sub menus? /rant

**Comment by conrad-vanl** [comment]
^^ Agree with @IsaacHardy. This view was supposed to be removed for now though, and replaced with the giving home screen 🤔
