### ISSUE TITLE
Newspring specific Spinner

### ISSUE THREAD

**Issue by IsaacHardy** [NewSpring/Apollos#331]
## Acceptance Criteria

- [ ] The NewSpring icon spinner should display where ever the current default spinner is shown.

**Comment by burkeshartsis** [comment]
@IsaacHardy was there ever consensus around the idea that Apollos uses native spinners so that the app feels more native. If this is a the desired UX (highly recommended) can issue can be closed?

**Comment by IsaacHardy** [comment]
@burkeshartsis This issue should be closed.
