### ISSUE TITLE
Login inputs

### ISSUE THREAD

**Issue by burkeshartsis** [NewSpring/Apollos#332]
## Acceptance Criteria

- [ ] Input validation text should be grammatically correct (no camel case)
- [x] Input labels should animate back into place correctly when deselected with no input.
- [x] Input labels shouldn't "bounce" between empty and filled state.

## Context

This appears to only be affecting the login inputs (give inputs seem ok but validation isn't handled consistently everywhere) but all platforms seem to suffer. Validation seems to be showing the variable name. When you select an input and deselect without inputing anything the label animates to an incorrect position. Labels seem to "bounce" between empty and filled input state. 

#### validation text
![screenshot_1518623515](https://user-images.githubusercontent.com/2053547/36215345-dcf0316e-1179-11e8-8916-b0b9550811fe.png)
#### label placement
![inputs](https://user-images.githubusercontent.com/2053547/36169122-4d2cb832-10c9-11e8-89b0-a3960817f8f5.gif)
#### "bouncing"
![jumpy](https://user-images.githubusercontent.com/2053547/36171860-28e5c672-10d2-11e8-8e09-cc2ee9d2d361.gif)

**Comment by conrad-vanl** [comment]
The stylistic issues have been fixed, it's just the validation messages that need tweaking.

**Comment by burkeshartsis** [comment]
For reference those were fixed in #323
