### ISSUE TITLE
Switch Video Player to Wistia from Ooyala

### ISSUE THREAD

**Issue by IsaacHardy** [NewSpring/Apollos#335]
## Acceptance Criteria

- [ ] Video player should be setup to display videos from Wistia instead of Ooyala

## Context

We are moving to Wistia for all of our video content. So we need to make changes that allow for this change within Apollos.

**Comment by conrad-vanl** [comment]
This is a heighliner change. `embedUrl` and `videoUrl` props can be updated on heighliner to point to wistia endpoints.

**Comment by IsaacHardy** [comment]
@conrad-vanl Could you elaborate a bit more regarding this solution?

**Comment by conrad-vanl** [comment]
Yup! We were talking about this a bit in the standup call this week. Basically, there are two resolvers in Heighliner that can be updated to point to wistia endpoints, and Apollos won't need any changes.

The first is here:
https://github.com/NewSpring/Heighliner/blob/alpha-2.0.0/src/expression-engine/models/content/resolver.js#L118-L131

The second is here:
https://github.com/NewSpring/Heighliner/blob/alpha-2.0.0/src/expression-engine/models/content/resolver.js#L86-L100

`videoUrl` should return the url of the actual video file, and that would be used by apollos to display the native player

`embedUrl` should return the url to wistia's web player for this video, and can be used as an iframe source to embed the video in a page using wistia's player.

**Comment by IsaacHardy** [comment]
Awesome! That is what I was looking for! I apologize if we spoke about this during our call. I remember the conversation but I didn't remember much of the details. 

I am going to go take a look at this!

**Comment by briankalwat** [comment]
@IsaacHardy is this complete?

**Comment by IsaacHardy** [comment]
This issue is done. Closing.
