### ISSUE TITLE
WEB: "Near My Location" feature 

### ISSUE THREAD

**Issue by IsaacHardy** [NewSpring/Apollos#337]
## Acceptance Criteria

- [ ] I should allow chrome to find my location to search for a group near me.

## Context

Currently on web, when attempting to use the "Near My Location" toggle, the display simply says "could not find your location" without asking for a prompt to my browser.

## UI Screenshot or Wireframe (optional)

![screen shot 2018-02-14 at 9 49 37 am](https://user-images.githubusercontent.com/10745699/36210584-ca1bdf1e-116c-11e8-9ec2-a659975988c3.png)

**Comment by conrad-vanl** [comment]
I believe this is related to using the non-secure (non-https://) version of the site. Try it with https://

We should redirect http traffic to https

**Comment by IsaacHardy** [comment]
@conrad-vanl That did it!
