### ISSUE TITLE
WEB: Giving Account Styles

### ISSUE THREAD

**Issue by IsaacHardy** [NewSpring/Apollos#342]
## Acceptance Criteria

- [ ] The styling for the web version of giving accounts show be less redundant and larger in width to display all of the desired content. 

## Context

Currently when creating or viewing an existing account on the giving page in web, there seems to be two vertical black closing buttons to send you back to the giving page. This works well on Native, but looks odd on web. Also, the width of this container could be larger for the content within. 

## UI Screenshot or Wireframe (optional)
![screen shot 2018-02-14 at 10 31 53 am](https://user-images.githubusercontent.com/10745699/36212642-7215ed04-1172-11e8-9985-9991fc2c79dd.png)

![screen shot 2018-02-14 at 10 40 43 am](https://user-images.githubusercontent.com/10745699/36213150-f4217e66-1173-11e8-9053-ac66bfc65be5.png)

**Comment by conrad-vanl** [comment]
I believe this is fixed in latest master, fixed in #297

**Comment by IsaacHardy** [comment]
Both of these were taken today at 4:15pm.

![screen shot 2018-02-14 at 4 15 09 pm](https://user-images.githubusercontent.com/10745699/36228516-6a6cf1c6-11a2-11e8-9146-b394f9348023.png)
<img width="581" alt="screen shot 2018-02-14 at 4 15 55 pm" src="https://user-images.githubusercontent.com/10745699/36228521-6d614a76-11a2-11e8-8027-c726357b4093.png">

**Comment by conrad-vanl** [comment]
@burkeshartsis do you remember what PR you saw this in?

**Comment by conrad-vanl** [comment]
NVM. It is in this PR, we must've just missed applying it to the edit account screens.

**Comment by conrad-vanl** [comment]
@burkeshartsis FWIW, this is an issue with I believe `asModal` being used in `AppRouter` on these screens, where the components are already modals so they don't need to be wrapped in `asModal`. If it's not that - it's something like that.....`@ui/Modal` is being rendered twice
