### ISSUE TITLE
ipad portrait nav

### ISSUE THREAD

**Issue by johnthepink** [NewSpring/Apollos#347]
- [x] ipad 2
- [x] ipad retina
- [x] ipad air
- [x] ipad air 2
- [x] ipad pro

![screenshot 2016-03-04 23 08 07](https://cloud.githubusercontent.com/assets/816517/13545560/6465c426-e25e-11e5-8566-d66d4340f345.png)

**Comment by jbaxleyiii** [comment]
@johnthepink this should be fixed in the latest build
