### ISSUE TITLE
Implement Analytics

### ISSUE THREAD

**Issue by conrad-vanl** [NewSpring/Apollos#347]
Todo; spec out this issue

## Acceptance Criteria

- [ ] It should [SPEC_DETAIL]

## Context

Given [CONTEXT] when [ACTION] then [RESULT]

**Comment by burkeshartsis** [comment]
Look into firebase as per Frank's questions.

**Comment by conrad-vanl** [comment]
FWIW, google analytics is used on Holtzman and is completely missing in Apollos.

**Comment by burkeshartsis** [comment]
Looking at Firebase for a moment it looks like we would just setup GA and add any additional configuration (if any at all) so that it's showing up as desired in Firebase.

**Comment by IsaacHardy** [comment]
It look like Google Analytics through Firebase will not be possible unless we eject from Expo. 

Stackoverflow on the issue: https://stackoverflow.com/questions/48867910/how-can-we-use-firebase-analytics-with-an-expo-based-react-native-app

Expo Forum Response from Dev: https://expo.canny.io/feature-requests/p/full-native-firebase-integration

Doesn't seem like Expo supports external native modules.

**Comment by IsaacHardy** [comment]
It seems that https://github.com/react-native-community/react-native-google-analytics is a possible solution.

**Comment by burkeshartsis** [comment]
It's very frustrating that Google would rename "Firebase Analytics" to "Google Analytics for Firebase" but not necessarily use an implementation that works with both analytics platforms. My guess is we will have to play with this to figure out exactly what will and will not work. From the sound of it you don't plan to use any other parts of the Firebase SDK so if there is a way to bridge data with a simple GA setup to Firebase we can probably go that route. Again, we'll probably have to get our toes wet to really find out.

**Comment by IsaacHardy** [comment]
@burkeshartsis We want to use Firebase Push Notifications as well. This is something we did in Holtzman (though it was disabled).

**Comment by conrad-vanl** [comment]
Make sure you check out https://docs.expo.io/versions/latest/guides/using-firebase.html @IsaacHardy @burkeshartsis

**Comment by conrad-vanl** [comment]
Ah, i was reading the comments in reverse order

**Comment by conrad-vanl** [comment]
I believe firebase push notifications should just work though, i don't think any thing on the app side is needed as push notifications are sent outside of the app scope

**Comment by conrad-vanl** [comment]
unless there is any UI in app that is displayed in response to the push notification.

**Comment by conrad-vanl** [comment]
but there are other options for push notifications that have better support for expo - https://docs.expo.io/versions/latest/guides/push-notifications.html

**Comment by FrankGrand** [comment]
We currently use Firebase for Push Notifications (we've created a Rock 'communication medium' that is dependant on Firebase), we also use it for deep/dynamic linking, and want to move analytics there if possible.  Based on the convo yesterday, I'd just want to fully understand the issues before making any final decisions.  While I'm sure there are alternative solutions for each piece (notifications, linking, analytics) there is definitely some value for us in having all that in one place

**Comment by conrad-vanl** [comment]
@IsaacHardy this issue is assigned to you, but would you like me to take it over?

**Comment by conrad-vanl** [comment]
@IsaacHardy gonna need to get a hold of these keys:

```
FABRIC_API_KEY
FABRIC_API_SECRET
```

annnnddd the google analytics tracking code, should look something like 'UA-XXXXXXXX-X'

**Comment by conrad-vanl** [comment]
you can add them to the keys repo thingy on github and i can grab them there

**Comment by IsaacHardy** [comment]
@conrad-vanl The Fabric vars can be found here: https://github.com/NewSpring/ops-settings/blob/master/sites/apollos/launch.json

Google Analytics can be found here: https://github.com/NewSpring/ops-settings/blob/master/sites/my.newspring.cc/production.settings.json
