### ISSUE TITLE
Look at touchable area on back button

### ISSUE THREAD

**Issue by conrad-vanl** [NewSpring/Apollos#350]
> Finally, I don't see this as an issue yet, but the back button on pages where you go into a devo or article or something is really hard to press.  It typically takes multiple presses to find the right space to get it to go back.  Not sure if it's just a sizing issue with the clickable space, or if it's something more complicated.

**Comment by IsaacHardy** [comment]
@conrad-vanl Reopening this issue. Back button on Android is still a mess.

**Comment by conrad-vanl** [comment]
@IsaacHardy according to @FrankGrand the issue is different now:

> No, this isn't an issue where you just can't tap it, the app gets stuck and no matter what you do you can't go back.  You have to restart the app.
