### ISSUE TITLE
Saved Payment cards not using specific CC type icons

### ISSUE THREAD

**Issue by richarddubay** [NewSpring/Apollos#355]
## Acceptance Criteria

- [ ] The app should show the icon of the specific type of saved payment account (credit card or bank account) on the saved payment card.

** This might be on your polish roadmap. Just something I noticed.

## Context

The current app shows the credit card type on the saved payment card. See screenshots. Also, it is a half-width card allowing two side-by-side if there are more than one

## UI Screenshot or Wireframe (optional)

Current App

![current app](https://user-images.githubusercontent.com/3229463/36398451-33206fb2-1595-11e8-8af3-7698a5d149f9.png)

Apollos

![apollos](https://user-images.githubusercontent.com/3229463/36398454-351a1d54-1595-11e8-8556-a42aa94511fa.png)

**Comment by burkeshartsis** [comment]
I'm going to assume this is dependent on #192
