### ISSUE TITLE
Topic Toggle Switches in Profile Section Flicker When Animating

### ISSUE THREAD

**Issue by briankalwat** [NewSpring/Apollos#362]
## Acceptance Criteria

- [ ] Toggle Switches should smoothly animate toggle position as well as color changes between enabled/disabled states.

## Context

When toggling topic switches in the profile section, the switches do not animate smoothly left/right or grey/green.

## UI Screenshot or Wireframe (optional)

[ScreenRecording_02-21-2018 17-14-32.MP4.zip](https://github.com/NewSpring/Apollos/files/1745920/ScreenRecording_02-21-2018.17-14-32.MP4.zip)

**Comment by IsaacHardy** [comment]
To add more to this issue, there seems to be a slight flicker when the toggle switch makes it switch to the other side. I believe you can see it one time in the MP4 above.

**Comment by briankalwat** [comment]
The issue I was ultimately trying to point out is that these don't animate like the same toggle switch for "Schedule Contribution" in the "Give Now" section (see below). Since these UI elements are identical, the user will expect them to function and animate the same way everywhere.

[GiveNowToggleRecording.zip](https://github.com/NewSpring/Apollos/files/1748064/GiveNowToggleRecording.zip)
