### ISSUE TITLE
Kick out to real browser instead of in-app browser for giving

### ISSUE THREAD

**Issue by conrad-vanl** [NewSpring/Apollos#363]
Read the title.

As per Jon Horton's advice.

**Comment by IsaacHardy** [comment]
@conrad-vanl I spoke with David from Life.church about this and I am wondering if we can just keep giving inside the in-app browser.

I would love to keep giving within the app itself, but that would be a feature later down the road.

**Comment by conrad-vanl** [comment]
We can easily disable the browser process altogether if you want on Apple. You might get with him and see what’s required, here’s the only info I can find: https://developer.apple.com/support/apple-pay-nonprofits/

**Comment by conrad-vanl** [comment]
@IsaacHardy there's currently some open bugs related to this. If we could disable the browser process altogether, that would reduce the complexity here. Thoughts?
