### ISSUE TITLE
Profile image uploading

### ISSUE THREAD

**Issue by conrad-vanl** [NewSpring/Apollos#365]
Now that we have S3 ability on alpha, we can properly test the profile upload flow.

It appears to work, but it takes some time for the image to upload and become processed to the extent it shows up in-app. We don't show any loading indication or anything like that, and it feels broken because of that.

How can we fix?

**Comment by burkeshartsis** [comment]
I took a look at this and it looks like `UserAvatarView` isn't aware that an image has been uploaded or changed. In looking at the underlying child components `Avatar` and `ImagePicker` I don't see any straight forward way to update the upstream parent components that the user has initiated or completed an an image upload. @Lepozepo is there a more elegant solution than setting state to `isLoading` in `UserAvatarView` and polling for photo url changes from Highliner? Can we do an optimistic update with the local path to the image while we wait for the upload to complete? It looks like the image is uploaded to rock and fetched by Apollos via Highliner (from Rock). Is that the correct flow? Is there something we could do in that process to better handle a loading state?
