### ISSUE TITLE
Update Giving receipt template to use preferred name instead of first name

### ISSUE THREAD

**Issue by jonhorton** [NewSpring/Apollos#365]
System is using my first name (Jonathan), even though Apollos uses my preferred name (Jon)

https://www.dropbox.com/s/8jj6u78ddhyki9x/Screenshot%202016-03-06%2008.31.47.png?dl=0

**Comment by jbaxleyiii** [comment]
@jonhorton I'm not sure whats happening here. I'll check into it thought. Fwiw, this is the existing code that is pulling NickName? https://github.com/NewSpring/Apollos/blob/master/give/observers/transactions.js#L176

**Comment by jonhorton** [comment]
@jbaxleyiii that's really odd. Especially if it's using the same name as the profile page.

The receipts I received for for a processed schedule. Could that have something to do with why?

**Comment by jbaxleyiii** [comment]
@jonhorton found the issue :)
