### ISSUE TITLE
Deploy Apollos 6.0.0 to Prod

### ISSUE THREAD

**Issue by IsaacHardy** [NewSpring/Apollos#369]
## Acceptance Criteria

- [ ] Apollos 6.0.0 should be deployed to NewSpring Production environment.

## Context

We need to research and construct a solution for deployment of Apollos 6.0.0 on the web.

**Comment by IsaacHardy** [comment]
@conrad-vanl I've looked into possibly using Netlify to deploy NewSpring's production of my.newspring.cc. It looks like we can create Netlify "Deploy Contexts" to set certain build variables from alpha/beta/prod. 

My questions revolve around how these build deploys will work with multiple domain names. I have not found anything that suggests that we can even use multiple domain names to deploy (publish) certain deploy previews manually.

**Comment by conrad-vanl** [comment]
@burkeshartsis I believe that the BAS/BAF team uses netlify a lot, so drew or nick might be able to help out with this question.

**Comment by IsaacHardy** [comment]
@burkeshartsis @conrad-vanl Spent today looking into this again. Still haven't found the best solution. I'm going to wait until we can speak with some of the other members of your team who might be able to help out.
