### ISSUE TITLE
Onboarding Slides for Apollos

### ISSUE THREAD

**Issue by FrankGrand** [NewSpring/Apollos#371]
## Acceptance Criteria

- [ ] It should [SPEC_DETAIL]

## Context

Given [CONTEXT] when [ACTION] then [RESULT]

**Comment by IsaacHardy** [comment]
@FrankGrand I don't remember what this issue is for?

**Comment by FrankGrand** [comment]
@IsaacHardy  This is to add the 'onboarding slides' to Apollos for first time app opens.

**Comment by burkeshartsis** [comment]
Needs new assets from design to reflect Apollos UI changes.

**Comment by richarddubay** [comment]
@burkeshartsis or @conrad-vanl Do we have components to build out a slider for this already? What if we used something like https://github.com/Jacse/react-native-app-intro-slider?

**Comment by conrad-vanl** [comment]
Yeah @richarddubay, that could work. We do have a horizontal slider in the app, but it's a little different.
