### ISSUE TITLE
Giving History Issues

### ISSUE THREAD

**Issue by richarddubay** [NewSpring/Apollos#374]
## Acceptance Criteria

- [ ] It should show a loading indicator when the user scrolls down to fetch more data.
- [ ] It should keep the giving history in the correct order after fetching.

## Context

Given that a user wants to see more of their giving history, when they scroll down to see more, then a loading indicator should display on the screen when the app is fetching more data.
Given that a user wants to see their giving history in the correct reverse chronological order, when the users has "fetched more", then they should still see their transactions in the correct order.

## UI Screenshot or Wireframe (optional)

Attaching two items here. One is an animated GIF of the "no loading indicator" problem. The other is an image of the top of the giving history feed AFTER having fetched more of my history.

No Loading Indicator

![no-loading-indicator](https://user-images.githubusercontent.com/3229463/36793142-947ec912-1c6a-11e8-85e5-ff7633e09dfe.gif)

Top of Giving History After Fetch

![messed-up-giving-hitory](https://user-images.githubusercontent.com/3229463/36793203-ca76574c-1c6a-11e8-802b-840a4a0bc48a.png)

**Comment by burkeshartsis** [comment]
Is it possible that the missing loading indicator is related #339?

**Comment by richarddubay** [comment]
@burkeshartsis Maybe? But the page kind of freezes while the new data is loading so I can't scroll up to the top to see. Maybe it's hiding behind the bottom card?

**Comment by IsaacHardy** [comment]
I've added #339 as a dependencies until we determine that it is not.

**Comment by IsaacHardy** [comment]
It does seem that #339 is the issue here. We will need to look more into this issue to solve why there is no loading indicator on the giving history tab. I recommend we separate the loading indicator requirement from this issue and place it into its own.
