### ISSUE TITLE
Card icon not in schedule button

### ISSUE THREAD

**Issue by samclaridge** [NewSpring/Apollos#378]
Card It's not showing on the main schedule page
https://www.dropbox.com/s/2m7h6amn3rgf509/Screenshot%202016-03-07%2018.57.50.png?dl=0

But shows up in the modal
https://www.dropbox.com/s/6es32hth4va7yyk/Screenshot%202016-03-07%2018.58.09.png?dl=0

**Comment by jbaxleyiii** [comment]
@samclaridge this is while the app is downloading your payment accounts. I'm working on speeding it up but I think this is expected behavior now. That is also the button when the user doesn't have a saved account
