### ISSUE TITLE
Schedule button active with no gift amount

### ISSUE THREAD

**Issue by samclaridge** [NewSpring/Apollos#379]
https://www.dropbox.com/s/3wsvvhki6gh73uh/Screenshot%202016-03-07%2018.59.29.png?dl=0

**Comment by jbaxleyiii** [comment]
fixed in upcoming build

<img width="903" alt="screenshot 2016-03-07 19 24 51" src="https://cloud.githubusercontent.com/assets/4967600/13588005/5dc617cc-e49a-11e5-8f6f-63ea3cc45151.png">
