### ISSUE TITLE
Update Apollos Assets

### ISSUE THREAD

**Issue by IsaacHardy** [NewSpring/Apollos#380]
## Acceptance Criteria

- [x] Apollos should display the new seasonal splash screen
- [x] Apollos on web should have most updated `.favicon`

**Comment by cdanwards** [comment]
@IsaacHardy Are we updating this to the Spring or to the Winter splash?

**Comment by IsaacHardy** [comment]
@cdanwards We should check with Creative to see when the new seasonal images will be coming in. We should use spring if possible.

**Comment by cdanwards** [comment]
@IsaacHardy I contacted Brandon to ask about the seasonal update and he said they're planning on launching March 18th. However, he said he's waiting on a fix for the resizing issue from you before he sent it off to creative.

**Comment by IsaacHardy** [comment]
@cdanwards I believe @richarddubay and I discussed those sizes last week. I have to get with him to remember those sizes.

**Comment by richarddubay** [comment]
@IsaacHardy https://docs.expo.io/versions/latest/guides/splash-screens.html told me to use 1242x2436 for the mobile image. I calculated 2224x2732 for the iPad version.

**Comment by cdanwards** [comment]
Sent the dimensions to Brandon and he sent the request off to Creative.

**Comment by cdanwards** [comment]
@burkeshartsis I've been investigating how to implement the newspring favicon in the app and that led me to the instructions listed in `Apollos/config/webpack.config.dev.js` and the corresponding prod file. Do you have any resources you could point me towards to help understand public path and %public_url% better?

**Comment by burkeshartsis** [comment]
I believe all you have to do is put a `favicon.ico` in the `/public` folder (root directory, not in `/src`)  and 🧙💥

**Comment by cdanwards** [comment]
And then it works.. I guess reading some of the comments made me think it was more complicated than it was. I thought I had to use PUBLIC_URL and then put it in the config file for an outside source. But it's working! So huzzah!

**Comment by cdanwards** [comment]
The only thing we're waiting for on this is the splash image from Creative which they will deliver tomorrow, March 15th.
