### ISSUE TITLE
Remove Back text btn from step 1 of forms

### ISSUE THREAD

**Issue by samclaridge** [NewSpring/Apollos#381]

**Comment by jbaxleyiii** [comment]
@samclaridge all forms? or just give?

**Comment by samclaridge** [comment]
Maybe just give for now? But maybe all eventually?

Samuel Claridge

— Sent from
https://polymail.io/

On Mon, Mar 07, 2016 at 9:24 PM James Baxley

<
mailto:James Baxley <notifications@github.com>
> wrote:

https://github.com/samclaridge
all forms? or just give?
