### ISSUE TITLE
Update meta titles

### ISSUE THREAD

**Issue by jonhorton** [NewSpring/Apollos#383]
/give/schedules: title="Schedule Your Giving"
/give/schedules/transfer: title="Transfer Your Giving Schedule"

I also noticed that all of the /profile/settings/* pages don't have custom title tags. They just read "First Last Name"

I think it would be nice to update those to reflect the page.  Thoughts?

**Comment by jbaxleyiii** [comment]
Yep! Thanks for auditing meat dat, it needs it!
