### ISSUE TITLE
Missing Punctuation

### ISSUE THREAD

**Issue by richarddubay** [NewSpring/Apollos#383]
## Acceptance Criteria

- [ ] It should show any punctuation in titles.

## Context

Given that a person reads the headlines of the content on our site or in our app, when a title displays then it should show the entire title including any punctuation.

## UI Screenshot or Wireframe (optional)

![screenshot 2018-03-06 10 39 21](https://user-images.githubusercontent.com/3229463/37041625-a73f38ec-212a-11e8-88d5-008869723000.png)

See the top left title and the return data in the Apollo Dev Tools. The title should read "Want To See The World And Make A Difference?" with a question mark at the end.

**Comment by conrad-vanl** [comment]
🤔

**Comment by conrad-vanl** [comment]
I bet `startCase` or `toLower` is stripping punctuation https://github.com/NewSpring/Apollos/blob/master/src/%40ui/FeedItemCard/index.js#L55

**Comment by conrad-vanl** [comment]
Closing in favor of #424
