### ISSUE TITLE
Scripture Formatting in Devotionals is Not Always Consistent

### ISSUE THREAD

**Issue by briankalwat** [NewSpring/Apollos#386]
## Acceptance Criteria

- [ ] Scripture data from API should be formatted consistently across all platforms.

## Context

When viewing a devotional that has a segment of scripture that includes headings, those headings do not correctly break on new lines on iPhone X like they do on other phones.

## UI Screenshot or Wireframe (optional)

![iphone8](https://user-images.githubusercontent.com/2465823/37098788-c029dc1e-21ec-11e8-8a45-136ae782b936.JPEG)

![googlepixel2](https://user-images.githubusercontent.com/2465823/37098794-c3c93d42-21ec-11e8-9074-f97c21c5a14e.PNG)

![iphonex](https://user-images.githubusercontent.com/2465823/37098804-c82c2598-21ec-11e8-8485-6f09bce6f4e5.PNG)

**Comment by IsaacHardy** [comment]
@briankalwat Are the first two examples from other phones and the latter from your iPhone X?

**Comment by briankalwat** [comment]
@IsaacHardy correct.

**Comment by conrad-vanl** [comment]
weeeeiiiirrrrrrdddddd
