### ISSUE TITLE
Devotional Content Hyperlink Color Inconsistencies

### ISSUE THREAD

**Issue by briankalwat** [NewSpring/Apollos#387]
## Acceptance Criteria

- [ ] Text colors for hyperlinks should be text colored with underlines.

## Context

When viewing a devotional, it appears that hyperlinks do not adhere to the text color or foreground color chosen in the light/dark switch. This is problematic because the brand green does not have good contrast with many study brand colors.

## UI Screenshot or Wireframe (optional)

![iphonexcolorissue](https://user-images.githubusercontent.com/2465823/37100792-dc566c18-21f1-11e8-94c5-1e2ff4497164.jpeg)

**Comment by IsaacHardy** [comment]
This is similar to #357. @briankalwat Is there anything within this issue that isn't covered in 357?

**Comment by briankalwat** [comment]
@IsaacHardy I suppose just the color of hyperlinks, but I've added a comment in the other issue.

**Comment by briankalwat** [comment]
@IsaacHardy re-opening this as it's currently an issue in Holtzman (we'll want to fix in Apollos eventually, but we want to keep existing issues separate from inconsistencies between Holtzman/Apollos (#357).

**Comment by conrad-vanl** [comment]
this can be easily done by over-writing the theme
