### ISSUE TITLE
Improve Card Slider Author UI to Support Multiple Authors/Speakers

### ISSUE THREAD

**Issue by briankalwat** [NewSpring/Apollos#388]
## Acceptance Criteria

- [ ] The cards should have a UI solution that can handle sermons with multiple speakers in an elegant fashion. If there are multiple speakers, let's at least divide their names by commas, etc. 

Is there another layout solution for these that is better for the Type icon, Authors, and Age metadata?

## UI Screenshot or Wireframe (optional)

![img_07a0c5b69007-1](https://user-images.githubusercontent.com/2465823/37101409-90a1888c-21f3-11e8-9f84-1ed1b849a46e.jpeg)

**Comment by IsaacHardy** [comment]
@briankalwat You've never met Brad Cooper Howard Frist Michael Mullikin Shane Duffey Jr.? 

PS: Good catch.
