### ISSUE TITLE
Update URL to Manage Group for group leaders

### ISSUE THREAD

**Issue by jonhorton** [NewSpring/Apollos#388]
Currently link to beta-rock.
Should link to https://rock.newspring.cc/groups/leader?GroupId=xxxxx

Also, is it possible to restrict this so it only shows up for the group leader?

**Comment by jbaxleyiii** [comment]
@jonhorton this is an env settings. It will be rock.newspring.cc on production.

We can show it only to the group leader if you are logged in. I'll take a look
