### ISSUE TITLE
Unable to search /groups/finder by group name

### ISSUE THREAD

**Issue by jonhorton** [NewSpring/Apollos#390]
Searched by group name + prefilled address
Searched by group name only

0 results returned

Test group: Rossie Bridges
Confirmed listed in beta-rock
- active
- public

**Comment by jbaxleyiii** [comment]
<img width="841" alt="screenshot 2016-03-07 22 03 30" src="https://cloud.githubusercontent.com/assets/4967600/13590742/792d8a52-e4b0-11e5-8b6b-787c1af46be5.png">

**Comment by jonhorton** [comment]
What the...

**Comment by jbaxleyiii** [comment]
https://my.newspring.cc/groups/finder/list/eyJuYW1lIjoiUm9zc2llIEJyaWRnZXMifQ==

**Comment by jonhorton** [comment]
Ahh I can reproduce now.

If ANYTHING is filled out in the address, it returns 0 
https://www.dropbox.com/s/94ov6bwqegzqrd5/Screenshot%202016-03-07%2022.07.14.png?dl=0

Which is difficult to accomplish, when it prefills my address.

Perhaps it would be better to allow a user to choose the way they want to search? ie., Group Name, Location, Campus?

**Comment by jbaxleyiii** [comment]
@jonhorton let me remove the limit then have you try it again

**Comment by jbaxleyiii** [comment]
@jonhorton I think this is "fixed" for launch. However I don't think this iteration of group finder will last us all that long haha.

**Comment by jonhorton** [comment]
Haha agreed! testing now

**Comment by jonhorton** [comment]
That worked for her group! Is Frank's group searchable?

**Comment by jonhorton** [comment]
nvm! Looked up frank in beta-rock and he's marked private.
