### ISSUE TITLE
Update totals to always use two decimal places

### ISSUE THREAD

**Issue by jonhorton** [NewSpring/Apollos#400]
Currently if a number ends in 0, the 0 is truncated. This doesn't happen on the giving receipt though.

**Comment by jonhorton** [comment]
Only showing single decimal on the successful give modal https://www.dropbox.com/s/1mjmmnwzzcupbx6/Screenshot%202016-03-08%2014.49.22.png?dl=0

**Comment by jbaxleyiii** [comment]
fixed
