### ISSUE TITLE
Giving to more than one fund breaks giving functionality for that user

### ISSUE THREAD

**Issue by IsaacHardy** [NewSpring/Apollos#405]
## Acceptance Criteria

- [ ] A User should be able to give to multiple funds.

## Context

If a user attempts to give to more than one fund, an error will occur that breaks giving functionality completely for that user. [LINK TO SENTRY ERROR](https://sentry.io/newspring-church/app/issues/494161014/)

## UI Screenshot or Wireframe (optional)

Attempting to give: 

![2018-03-15 09 41 35](https://user-images.githubusercontent.com/10745699/37466958-5cd63dfc-2835-11e8-962d-8ac0010d6d0d.gif)

![2018-03-15 09 41 52](https://user-images.githubusercontent.com/10745699/37466976-673d6298-2835-11e8-874e-951fa7bdb284.gif)

![2018-03-15 09 42 09](https://user-images.githubusercontent.com/10745699/37466981-69a63f82-2835-11e8-89d5-c4201cbaf1fb.gif)

Trying to navigate back to giving: 

![2018-03-15 09 42 49](https://user-images.githubusercontent.com/10745699/37466987-6e99470a-2835-11e8-8968-a9b04f59047b.gif)

**Comment by Lepozepo** [comment]
Mmm, there's definitely an error in `StatusMessage` Line 28 on `didPass`, it looks like it should be `get('details, '1.amount', 0).toFixed()` instead but I'll have a second look at the responses coming from the server also. Will be looking into this on Wednesday/Thursday.

**Comment by conrad-vanl** [comment]
I'm taking this
