### ISSUE TITLE
Giving Graph displays no data points on native platforms

### ISSUE THREAD

**Issue by IsaacHardy** [NewSpring/Apollos#406]
## Acceptance Criteria

- [ ] Dashboard graph should display giving data on native platforms.
- [ ] Dashboard graph should be consistent with actually giving data.
- [ ] Dashboard graph should update after giving has returned from in-app-browser.

## UI Screenshot or Wireframe (optional)

No data on Giving platform: 
<img width="289" alt="screen shot 2018-03-15 at 10 44 19 am" src="https://user-images.githubusercontent.com/10745699/37470861-d37fcf1e-283e-11e8-8944-09ed9ee39de5.png">
<img width="480" alt="screen shot 2018-03-15 at 10 51 08 am" src="https://user-images.githubusercontent.com/10745699/37470863-d5a5e38c-283e-11e8-9475-0d2d71854f15.png">

**Comment by burkeshartsis** [comment]
Related issue #408

**Comment by richarddubay** [comment]
@IsaacHardy @burkeshartsis I'll take a look at this when I'm working on this, but it looks like the graph is showing the total giving all-time instead of just for this year. Could be _slightly_ confusing. ;)

**Comment by burkeshartsis** [comment]
I would agree that current year, or maybe better the last 12 months, makes the most sense given the 12 month break down. Showing the last 12 months may be more ideal that way you don't get an empty chart at the beginning of the year. At the same time it's weird to look at old data when so many things financial are displayed annually (i.e. giving history tab). 🤔

**Comment by richarddubay** [comment]
Our current app does current year...so that's probably what I'll look to do. We can always make it better later.
