### ISSUE TITLE
Next button disabled on the address page of adding a new payment account

### ISSUE THREAD

**Issue by richarddubay** [NewSpring/Apollos#409]
## Acceptance Criteria

- [ ] It should allow a person to click the "Next" button when all necessary items have been added for the address when adding a new payment account.

## Context

Given that a user has entered all of the correct information for the address when attempting to add a new payment account then they should be allowed to click or tap the "Next" button. Right now it is disabled.

## UI Screenshot or Wireframe (optional)
![broke](https://user-images.githubusercontent.com/3229463/37600834-d5971f82-2b5e-11e8-9344-66db08423f51.png)

**Comment by richarddubay** [comment]
@burkeshartsis @IsaacHardy This will have to be fixed before we launch. Are you guys okay with moving this into the current sprint?

**Comment by burkeshartsis** [comment]
@richarddubay if there is truly no way to advance to the next screen than you are correct that we'll need to address this issue. Is there really no way to advance? Is it waiting for data in the second address field or something (easy fix). I would say don't worry too much about prioritizing issues as we'll likely get a bunch in the next couple days. Just make sure to label them and put them in the backlog.

**Comment by richarddubay** [comment]
@burkeshartsis Yeah, unless you add something to address 2, then the Next button doesn't become enabled. I'll just move this to the backlog then.

**Comment by burkeshartsis** [comment]
Should be a pretty easy fix than. Just a tweak to the `YUP` validation.

**Comment by richarddubay** [comment]
Yup. ;)

**Comment by conrad-vanl** [comment]
I believe the above is incorrect.

**Comment by burkeshartsis** [comment]
Hey @richarddubay I'm not able to reproduce this issue right now. Do you mind either walking me through this or trying again with the software keyboard showing (⌘K or Hardware>Keyboard>Toggle Software Keyboard)

**Comment by richarddubay** [comment]
@burkeshartsis So I tested again and I'm able to reproduce. I'm currently on the alpha branch. Here is what I did:

- I start up the app and run it in the iOS simulator.
- I go to giving and make sure I'm signed in.
- I enter an amount to give.
- I tap on "Review Contribution".
- I tap on "Change Payment Method".
- I tap on "Enter New Payment".
- I tap "Next" on the first screen.
- On the billing address screen I see that the "Next" button is disabled even though all of my address is automatically filled in except for the second address.

I've added a screenshot below of the screen with my cursor in the zip code field and the keyboard showing for you.

Does any of this help?

![screenshot 2018-03-28 09 17 56](https://user-images.githubusercontent.com/3229463/38031360-ffb2ae74-3268-11e8-9070-ffd4eb2fe5f8.png)

**Comment by conrad-vanl** [comment]
Ok, @burkeshartsis I can reproduce following those steps exactly. I have a feeling it actually could be related to the state field - I have "Texas" in my profile, but the state dropdown is still showing "South Carolina", the default value. Maybe you can log props on mount and see what's going on....

**Comment by conrad-vanl** [comment]
Interestingly enough, I can't reproduce with the Aaron Attendee account, even following those steps.

**Comment by richarddubay** [comment]
@burkeshartsis @conrad-vanl It says "South Carolina".
