### ISSUE TITLE
Build H1, H2, H3, H4, H5, H6, H7, and P Components

### ISSUE THREAD

**Issue by Lepozepo** [NewSpring/Apollos#41]
## Acceptance Criteria

- [x] It should create a vertical rhythm function that takes in a base value (16).
- [ ] They should all use colfax-web
- [x] H1 font-size is 46.4px | rhythm(2.9)
- [x] H2 font-size is 37.6px | rhythm(2.35)
- [x] H3 font-size is 28.8px | rhythm(1.8)
- [x] H4 font-size is 22.4px | rhythm(1.4)
- [x] H5 font-size is 17.792px | rhythm(1.112)
- [x] H6 font-size is 14px | rhythm(.875)
- [x] H7 font-size is 12.448px | rhythm(.778)
- [x] P font-size is 17.792px | rhythm(1.112)

## Context

Holtzman/stylesheets/_vars.scss

**Comment by burkeshartsis** [comment]
>They should all use colfax-web

It doesn't look like we'll be able to use Colfax unless they have already secured an app license. I know you know this @conrad-vanl I just wanted to leave a note so you can be sure to mention to this to NewSpring in the next standup. FWIW, the type foundry does have special licensing available upon request.

https://processtypefoundry.com/licensing/other-licenses
