### ISSUE TITLE
Terms of Service is pre-enabled when creating a new account

### ISSUE THREAD

**Issue by cdanwards** [NewSpring/Apollos#413]
## Acceptance Criteria

- [ ] The slider indicating that the user agrees to the terms of service should default to "not agree" so that there is an action indicating that they agree to the terms.

## Context

Given a new user is creating an account then the agree to terms of service should not be pre-enabled or defaulted to yes.

**Comment by conrad-vanl** [comment]
Are we sure that this is correct? Or are we blindly following this tester's advice? The current app defaults to having the terms and condition CHECKED to yes.

**Comment by IsaacHardy** [comment]
I instructed @cdanwards to create first, ask questions later. We can discuss this internal and close it if we need to.
