### ISSUE TITLE
Viewing existing schedules crashes the app

### ISSUE THREAD

**Issue by cdanwards** [NewSpring/Apollos#414]
## Acceptance Criteria

- [ ] When a user goes to the giving dashboard then to review schedule, the schedule details should load.
- [ ] After creating a new schedule, the user should be able to view/edit that schedule.

## Context

Currently when going to review an existing schedule, the app crashes and restarts. Also, when a user creates a new schedule, they are not able to view/edit those newly created schedules.

## UI Screenshot or Wireframe (optional)

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/8878532/37674974-6ca55b50-2c4a-11e8-99f5-bb42103d01f4.gif)

**Comment by conrad-vanl** [comment]
> existing schedule

Does this mean a schedule they created _before_ beta testing - like on the production app - or a schedule they created inside of the app they can't view?

If the first one - I need to get my hands on an account with an existing schedule so I can see what's going on.

**Comment by cdanwards** [comment]
@conrad-vanl The first option is correct so far as I've seen from the bugs reported.

**Comment by conrad-vanl** [comment]
In that case - I need to get my hands on a user account that exhibits this issue. There's no way I know of to create a user with an existing schedule

**Comment by conrad-vanl** [comment]
Marking as blocked until I can get access to a user account that shows this issue (or insight on how to create this issue on a _new_ user account)

**Comment by conrad-vanl** [comment]
@IsaacHardy @FrankGrand need help on this to resolve....can't replicate with our own accounts, it sounds like it has to do with pre-existing schedules on other accounts.

**Comment by richarddubay** [comment]
Okay @conrad-vanl, I tested this. I've attached a GIF of what I did, and a screenshot of the resulting page. Let me know if this helps at all.

![2018-03-30 18 40 11](https://user-images.githubusercontent.com/3229463/38156232-6eca2408-344a-11e8-878b-36a401097d6c.gif)

![screenshot 2018-03-30 18 40 33](https://user-images.githubusercontent.com/3229463/38156236-74ee7776-344a-11e8-8fa1-be9ed6ff2bb5.png)

**Comment by FrankGrand** [comment]
Let me know if this isn't enough @conrad-vanl and we can figure something else out in setting you up.

**Comment by conrad-vanl** [comment]
Hmmm...not really. This helps me narrow down to the line of code, but it doesn't help reveal what's going on.

This line of code: https://github.com/NewSpring/Apollos/blob/alpha/src/give/ScheduleDetails/ScheduleTransactionHistory.js#L38

Which I _believe_ maps to this query: https://github.com/NewSpring/Apollos/blob/alpha/src/%40data/withScheduledTransaction/index.js#L20-L23

**Comment by conrad-vanl** [comment]
@FrankGrand / @IsaacHardy ^^

**Comment by IsaacHardy** [comment]
@conrad-vanl After some finagling, I've figured out the issue with this "issue". 

The users who reported this bug, have accounts AND schedules in the beta environment that are linked to the production NMI settings.

This is what causes the crash. I'm closing this issue after confirming these findings.
