### ISSUE TITLE
Scheduling a new recurring gift with existing ACH

### ISSUE THREAD

**Issue by cdanwards** [NewSpring/Apollos#415]
## Acceptance Criteria

- [ ] When creating a new recurring gift, a user should be able to use an existing ACH account.

## Context

Currently, when a user tries to set up a new recurring gift using an existing ACH account, the action fails and the user is prompted with an error screen.

## UI Screenshot or Wireframe (optional)
![file_003 - will polley](https://user-images.githubusercontent.com/8878532/37675444-a093f01a-2c4b-11e8-9b1e-f6b80cde62d2.png)

**Comment by conrad-vanl** [comment]
Not convinced it's related to just ACH, had some similar issues with CC. Investigating. This sandbox environment is weird.
