### ISSUE TITLE
Confusion around the Secured Web Checkout

### ISSUE THREAD

**Issue by cdanwards** [NewSpring/Apollos#416]
## Acceptance Criteria

- [ ] When giving in IOS, the flow of buttons and text should give clear descriptions of what is happening when selecting.

## Context

Currently, some users are getting confused by the same button text being present in `give/Checkout/PaymentConfirmation` and `RestoredCheckout`. There were multiple users who believed they were giving twice.

**Comment by conrad-vanl** [comment]
@burkeshartsis this might be good for you to tackle. We have some deviations in these two screens with what's in their current app. This is iOS only, fwiw. I think we need to work on word-smithing a bit (maybe change the copy in the first "Give" button to be "Continue" or "Finish in safari" something) and clean up visual presentation some.

**Comment by IsaacHardy** [comment]
Reopening issue for better communication to giving flow.

**Comment by IsaacHardy** [comment]
The requested solution is to remove "Continue on Safari" and replace it with "Give with ####". The safari screen would then present a button with "Confirm"
