### ISSUE TITLE
NewSpring Store Link breaks on mobile

### ISSUE THREAD

**Issue by cdanwards** [NewSpring/Apollos#417]
## Acceptance Criteria

- [ ] When selecting a link, the user should be directed to the linked page on mobile.

## Context

Currently, on mobile but not web, selecting certain links in articles that have been created in Expression Engine using the link builder are breaking.

## UI Screenshot or Wireframe (optional)
![ezgif com-video-to-gif 1](https://user-images.githubusercontent.com/8878532/37677418-62e97f7c-2c51-11e8-9b3e-2b16dd24e98c.gif)

**Comment by conrad-vanl** [comment]
@cdanwards can I get an example of an article/story/content that is doing this? The GIF above doesn't appear to show it, and I'm having trouble finding one with a broken link.

**Comment by cdanwards** [comment]
@conrad-vanl [Here is the article on the website] (https://newspring.cc/news/new-kidspring-album-available-now) that everyone is referencing. When you select the "NewSpring Store" button after the image is what's breaking.

**Comment by IsaacHardy** [comment]
@cdanwards I'm slightly confused here. Is there more information you can give regarding this issue?
