### ISSUE TITLE
Initial Schedule Giving Amount defaulting to 0 when reviewing contribution

### ISSUE THREAD

**Issue by cdanwards** [NewSpring/Apollos#419]
## Acceptance Criteria

- [ ] When a user enters a contribution then selects it to be a scheduled amount, that amount should be consistent through the whole checkout process.

## Context

Currently when a user creates a new scheduled giving amount, the amount displayed in the final review screen is $0.

## UI Screenshot or Wireframe (optional)
![42189 - jacob morrison](https://user-images.githubusercontent.com/8878532/37678397-53f35e36-2c54-11e8-933d-f16afc750f21.jpg)

**Comment by conrad-vanl** [comment]
I am having trouble replicating this issue. It seems to be working correctly for me. Did we receive better replication steps?

![img_0833](https://user-images.githubusercontent.com/103927/37727586-3956cc54-2d06-11e8-8bb0-679c89f23728.png)

**Comment by cdanwards** [comment]
@conrad-vanl it's the screen after the one you provided that is displaying a total of $0.

**Comment by conrad-vanl** [comment]
The screen after that is the "Success" screen. The screenshot I included above is of the same screen you posted above, except when I tried to replicate it, I couldn't get it to break.

**Comment by conrad-vanl** [comment]
As per @IsaacHardy he's saying you tap the button in the webview and the webview "resets" to the error state at the beginning of the issue.
