### ISSUE TITLE
Devo Header Size

### ISSUE THREAD

**Issue by cdanwards** [NewSpring/Apollos#420]
## Acceptance Criteria

- [ ] Headers and other text should scale and size correctly regardless of the size of the word.

## Context

Currently on some devos that have longer words in the title, the title words are being wrapped to the line below.

## UI Screenshot or Wireframe (optional)

![img_0112 - brandon wilson](https://user-images.githubusercontent.com/8878532/37713275-c0c8a37a-2cec-11e8-981d-6a1b815cb782.JPG)

**Comment by conrad-vanl** [comment]
@burkeshartsis comparing to the current app, it appears that are heading size is just too large. Thoughts?

**Comment by burkeshartsis** [comment]
Yeah there is no way to handle this better without decreasing font size or changing the copy. I'll look at the current typography component being used and check Holtzman to see what inconsistencies there might be.
