### ISSUE TITLE
Any Campus dropdown menu defaults to Aiken

### ISSUE THREAD

**Issue by cdanwards** [NewSpring/Apollos#421]
## Acceptance Criteria

- [ ] After a user's campus has been set, any campus dropdown menu should default to the selected campus.

## Context

Currently there's several users who have the campus dropdown defaulting to Aiken. This is intended functionality when the campus is not set. This might be due to the location of setting the campus not being very clear in the personal settings.

**Comment by conrad-vanl** [comment]
I am trying to understand if this is a regression from the current app or a suggestion of enhancement. My profile has an a campus selected, and when I try to give or something that displays a campus dropdown field, that campus is selected. So I believe that correctly works. However, if I have no campus selected in my profile, it defaults to the first campus (Aiken).
