### ISSUE TITLE
Welcome to NewSpring Email

### ISSUE THREAD

**Issue by cdanwards** [NewSpring/Apollos#422]
## Acceptance Criteria

- [ ] When a user signs up for an account on the NewSpring app, they should be sent an email detailing the information they used to sign up.

## Context

Currently, the email being sent to new users is not supported in most browsers and email clients.

**Comment by Lepozepo** [comment]
@conrad-vanl the email is definitely sent by rock, there isn't much we can do except not trigger it. Holtzman previously had a bug where it would just fail to send emails after registering a new user.

**Comment by conrad-vanl** [comment]
@IsaacHardy or @richarddubay do you think someone on your end that's more familiar with Rock can look into this?

**Comment by IsaacHardy** [comment]
@conrad-vanl We'll look into it. Assigning it to me for now.
