### ISSUE TITLE
Results list to remember scroll position when returning to results after looking at a group page

### ISSUE THREAD

**Issue by samclaridge** [NewSpring/Apollos#424]

**Comment by johnthepink** [comment]
I initially thought we could use window.history.back for this, and it works, but it's probably not ideal as someone may land on a group page without having previously visited the site. In that case, it would take them back to whatever site they were on previously, or do nothing.

It may be possible to check the router's history, and then choose whether to use history.back or the actual link to the results?

**Comment by jbaxleyiii** [comment]
@johnthepink thats a great thought
