### ISSUE TITLE
Punctuation and capital lettering missing on newsfeed.

### ISSUE THREAD

**Issue by cdanwards** [NewSpring/Apollos#424]
## Acceptance Criteria

- [ ] Titles of articles, devotionals, sermons should display with all capitalization and punctuation.

## Context

Currently some titles are missing punctuation and the intermedial capitalization in NewSpring.

## UI Screenshot or Wireframe (optional)
![screen shot 2018-03-22 at 1 25 42 pm](https://user-images.githubusercontent.com/8878532/37787079-919d5760-2dd4-11e8-9b1e-3fd9ee4b744a.png)

**Comment by IsaacHardy** [comment]
FYI, this is beta-my.newspring.cc. Currently, that is pointed to `alpha` environments.

**Comment by IsaacHardy** [comment]
Related to #383.

**Comment by conrad-vanl** [comment]
> I bet `startCase` or `toLower` is stripping punctuation https://github.com/NewSpring/Apollos/blob/master/src/%40ui/FeedItemCard/index.js#L55
