### ISSUE TITLE
One time schedules don't reflect that in the active schedules list

### ISSUE THREAD

**Issue by jonhorton** [NewSpring/Apollos#425]
I created a one time schedule for today.
It processed great and sent a receipt via email and showed up in my history.
https://www.dropbox.com/s/esv80f4ux4daegl/Screenshot%202016-03-09%2021.15.56.png?dl=0

It feels odd that the one time schedule is still in the active schedules list. Also, when I click on it, I have the option to stop gift.

I think we need a better UI for those. Or perhaps schedules that are one time disappear after the date they start.

Thoughts?

**Comment by jbaxleyiii** [comment]
fixed and deploying
