### ISSUE TITLE
NewSpring Leaf elongated on profile tab

### ISSUE THREAD

**Issue by cdanwards** [NewSpring/Apollos#426]
## Acceptance Criteria

- [ ] When a user is missing a profile picture, there should be a newspring leaf logo in its place.

## Context

Some users have reported that the leaf image is elongated on Android.

## UI Screenshot or Wireframe (optional)

![screenshot_20180320-142839 - caroline tate](https://user-images.githubusercontent.com/8878532/37788594-322b793e-2dd8-11e8-9d43-42a7e22821d4.png)

**Comment by conrad-vanl** [comment]
This is really because Android doesn't have native ability to blur on React Native. Since the background image isn't blurred, it appears elongated in this instance. From a visual perspective, what would be the best fix for android?
