### ISSUE TITLE
Inactive button "Contact Us" on bottom group finder page

### ISSUE THREAD

**Issue by IsaacHardy** [NewSpring/Apollos#428]
## Acceptance Criteria

- [ ] The "Contact Us" button on the bottom of the group finder page should be clickable on android devices.

## Context

When searching in group finder on Android, below the results is a "Contact Us" button that should take you to a form. However, on Android the button cannot be clicked.

**Comment by conrad-vanl** [comment]
@burkeshartsis throwing this over to you. I can't track down the issue, I'm hoping you might have more insight on this. It's this button - https://github.com/NewSpring/Apollos/blob/alpha/src/group-finder/AdUnit.js#L17

seems to work on ios without issue.
