### ISSUE TITLE
Update user account last login date on Apollos sign in

### ISSUE THREAD

**Issue by jonhorton** [NewSpring/Apollos#430]
It would be great to update the Last Login Date column on the user account section in Rock whenever a person signs in to Apollos. This way we can get an accurate assessment of a person's activity + verify they are able to sign in!

https://www.dropbox.com/s/pckci66u03vuzpo/Screenshot%202016-03-10%2022.35.34.png?dl=0

**Comment by jbaxleyiii** [comment]
fixed
