### ISSUE TITLE
View and filter by family and date on giving history

### ISSUE THREAD

**Issue by jbaxleyiii** [NewSpring/Apollos#443]
This brings support parity to F1. Use the filter UI from groups. Lets use two date inputs to setup a filterable date range. We will also remove the infinite scroll in favor of show more + loading.

@samclaridge would you mind attaching a dropbox screenshot of that filter UI here?

**Comment by samclaridge** [comment]
@jbaxleyiii https://www.dropbox.com/s/l0xppm6ncmu7v7v/Screenshot%202016-03-28%2010.38.12.png?dl=0
