### ISSUE TITLE
Add pending status to Rock Financial model and pull it in via NMI

### ISSUE THREAD

**Issue by jbaxleyiii** [NewSpring/Apollos#448]
@benwiley @dcs619 I'm thinking a `DefinedType` for transaction status might be a good way to go about this? Then add `Status` to the transaction model and set the `DefinedType` value for the status of `pending`, `complete`, `failed`. It would be nice, although not sure if possible via NMI (I'll check) to pull the reason for failure too. I'm planning on chatting with Spark tomorrow about this.

> It doesn't *look* like NMI gives a reason for failed charges but I'm still looking into it

We also should sync the status and show a user a gift is pending on the UI cc @samclaridge

**Comment by dcs619** [comment]
@jbaxleyiii @samclaridge 

 ![](https://media.giphy.com/media/RaexEH6VfoU0g/giphy.gif)
