### ISSUE TITLE
Sermons slow to load / do not load

### ISSUE THREAD

**Issue by cdanwards** [NewSpring/Apollos#455]
## Acceptance Criteria

- [ ] When selecting a sermon on the Sermons tab, sermon assets should load.

## Context

Currently when navigating to a sermon on the Sermons tab, sermon content isn't loading or is taking 7+ seconds to load.

## UI Screenshot or Wireframe (optional)

![screenshot apr 4 2018 9_46_47 am - jonathan evans](https://user-images.githubusercontent.com/8878532/38315187-ee419c94-37f5-11e8-86d1-c72f1ac92325.png)

**Comment by conrad-vanl** [comment]
This is kinda fixed in #464

**Comment by cdanwards** [comment]
@IsaacHardy as Conrad mentions above, the loading state is better, but there still is a lag in load time.
