### ISSUE TITLE
Creating Schedules from "General Fund" or "Campus Expansion" Pages [Web]

### ISSUE THREAD

**Issue by cdanwards** [NewSpring/Apollos#457]
## Acceptance Criteria

- [ ] Whenever a user is on the General Fund or Campus Expansion pages in the Give Now tab, if they choose to make a contribution they should be able to make that into a scheduled contribution.

## Context

Currently when someone is on the General Fund or Campus Expansion pages and tries to set up a schedule, that schedule is not present under the "Active Schedules" section of the giving dashboard.

Recreate by: 
1) Sections
2) Give
3) Give Now
4) Select "General Fund" or "Campus Expansion"
5) Create recurring giving on that page
6) Go through giving flow
7) After success, go to Dashboard and that schedule will not appear under "Active Schedules"

**Comment by conrad-vanl** [comment]
This appears to be related to #408 and is very hit or miss (when I went through the flow it worked fine). Investigating a better fix. Closing in favor of #408
