### ISSUE TITLE
Change Payment Method Button [Android]

### ISSUE THREAD

**Issue by cdanwards** [NewSpring/Apollos#461]
## Acceptance Criteria

- [ ] User should be able to select the Change Payment Method button on the Review Contributions screen.

## Context

Currently this button is difficult to select on Android.

**Comment by conrad-vanl** [comment]
Agree this is a big nuisance. [`hitSlop`](https://facebook.github.io/react-native/docs/touchablewithoutfeedback.html#hitslop) probably to the rescue :)

**Comment by richarddubay** [comment]
@conrad-vanl If you get a minute, can you please maybe post a GIF of how hard it is to hit that button? I had Frank test it a bit ago and he didn't really have a problem. So I'm unsure if this has to be fixed. I don't actually have an Android device and I don't experience this problem in the simulator. Thanks!
