### ISSUE TITLE
Unable to reset password for F1 migrator account

### ISSUE THREAD

**Issue by jonhorton** [NewSpring/Apollos#468]
Hey! This bug was reported by Blake Jordan (WR-1141), and I was just able to confirm it with a separate account.

**Steps to Reproduce**
- User should have a Rock login account configured with with type of F1 Migrator.
- Created a separate inFellowship account of the same email address
- Visit my.newspring.cc and try to reset password using the same email address of the account
- Click on the reset password link in email and enter a new password
- On clicking enter, I get the following error: https://www.dropbox.com/s/bjl0piwhlyezt7h/Screenshot%202016-03-28%2020.56.14.png?dl=0

**Buggy Behavior**
- Password is not changed, though I'm logged in via the reset password link.

**Expected Behavior**
- F1 Migrator account is converted to type Database and password is reset when using the forgot password form

**Notes**
After the above testing, I signed in with the correct F1 Migrator password, which properly changed the account type to database. Then I signed out, and tried the forgot password form again.

On clicking the link, i was able to successfully change my password.

This leads me to believe that the issue lies within the F1 Migrator type. Since we are sending the email to the address on file, would it make sense to just convert the f1 migrator account to DB on a reset, then update the password?

**Comment by jbaxleyiii** [comment]
@jonhorton I was actually just working on that and it is now fixed in production :+1:

See PR #466

**Comment by jbaxleyiii** [comment]
@jonhorton I also responded back to blake and let him know its fixed

**Comment by jonhorton** [comment]
@jbaxleyiii awesome! :+1: Just confirmed fixed on my end as well. Hopefully this will also solve the issue for blake as well and cut down on some issues with F1 accounts!
