### ISSUE TITLE
Create UI component strategy

### ISSUE THREAD

**Issue by conrad-vanl** [NewSpring/Apollos#47]
## Acceptance Criteria

- [ ] It should produce new issues
- [ ] Have strategy for in place for porting UI, focus on primitives for now

**Comment by burkeshartsis** [comment]
After a rather exhaustive review of various options and a number of meaningful conversations with the rest of the team we have settled on the following.

## Folder Structure

Component folder structure should look something like
```
/component-name
    component-name.tests.js
    component-name.stories.js
    index.js
```
Modules containing multiple components that make up a given UI or feature set should be structured as such:
```
/module-name
    module-name.tests.js
    module-name.stories.js
    index.js*
    /component-name**
        component-name.tests.js
        component-name.stories.js
        index.js*
        component-name.js
        subcomponent-name.js
```
* `index.js` should export all necessary components of a given module/component. Effectively representing a module/components "public API."
** if a component lacks sufficient complexity and thus does not warrant tests and stories this folder can be omitted in a named component file in the parent directory (e.g. `/module-name/component-name.js`)

## File Structure

All components should be pure whenever possible. Write tests to assert this. Functional components should be used whenever possible. If you don't need React's component lifecycle methods or component state use an optimized functional component using Recompose higher order components. For consistency and easy of maintenance components should roughly aim be structured like the examples below.

### Functional Components
```
// Direct imports
import { compose } from 'recompose';

import namedExport from 'absolute-file-path/folder/';
import namedExport from './relative-file-path';

const enhancer = ( ... ) => compose(
  /* Include your components higher order components here. This will look will often look something
   * like this.
   * 
   * ... compose(
   *   pure,
   *   withTheme(({ theme: { breakpoints = {} } = {} }) => ({ breakpoints })),
   *   ...)
   */

const component = enhancer(( ... ) => {
  return (
    ...
  );
}

export default enhancer;
```

**Comment by burkeshartsis** [comment]
## Animations

For the time being we are going to stay focused on the "write once, use everywhere" mantra this project is upholding. Practically, that means we leverage the React Native Animated API heavily and do what we to ensure we keep things on the native thread.
