### ISSUE TITLE
"Campus expansion" fund name is cut off on iPhoneX

### ISSUE THREAD

**Issue by IsaacHardy** [NewSpring/Apollos#471]
## Acceptance Criteria

- [ ] Fund names should display without being cut off on iPhoneX.

## Context

This does not take place on the simulator, but I was able to replicate on a actual iPhone X device.

**Comment by conrad-vanl** [comment]
@IsaacHardy I'm not seeing this on my iphone. HOWEVER, if I turn on accessibility mode and increase font size, I do see fund sizes cut off. Can we verify if that's what's going on on Michael's phone (I'm assuming that's where this originated?). If so, I believe #484 is likely the incorrect fix.

**Comment by IsaacHardy** [comment]
Closed in favor for #494
