### ISSUE TITLE
Rock Sync Validation

### ISSUE THREAD

**Issue by johnthepink** [NewSpring/Apollos#48]
During a sync from Rock to Apollos, I received an email address like this: "meow.@gmail.com". Our email regex says this is invalid. I found [Rock's email validation regex](https://github.com/SparkDevNetwork/Rock/blob/6580444864035a4a67ea09e98166827aa3675863/Rock/Utility/ExtensionMethods.cs#L1283), which says that email is valid.

We could deal with this by:

1. Switch to Rock's regex
2. Reject emails from Rock that don't match our regex
3. Don't validate emails on sync from Rock
4. Use Rock's regex on sync from Rock

I've run in to a few issues like this when validating data received from Rock. For instance, we had a validation on birth year that it could not be less than 1900, but apparently there are people in Rock with birth years before 1900. I've dealt with those temporarily by turning off that validation.

**Comment by jbaxleyiii** [comment]
not needed anymore
