### ISSUE TITLE
Unable to remove a saved account

### ISSUE THREAD

**Issue by jonhorton** [NewSpring/Apollos#492]
I created a one time schedule on 3/12 and saved my payment info during that time.

I'm unable to give with that saved payment account.
I'm also unable to delete it.

When I click the remove link, it's visually removed, however when I refresh (even after waiting 1 minute or longer), the account is still under my saved payment accounts. :(

It's worth noting that I can remove a payment account saved via /give/now and it does remove it.

**Comment by jbaxleyiii** [comment]
@jonhorton how did you save your payment during the one time schedule? You shouldn't be able to save a payment when creating a schedule?

**Comment by jonhorton** [comment]
Just responding here what I did in person.  I believe the payment was saved
with a prior schedule.  But if that is technically impossible, then I must
have saved it previously, then used it to set up a one time schedule.

On Fri, Apr 22, 2016 at 8:35 PM, James Baxley <notifications@github.com>
wrote:

> @jonhorton <https://github.com/jonhorton> how did you save your payment
> during the one time schedule? You shouldn't be able to save a payment when
> creating a schedule?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/NewSpring/Apollos/issues/492#issuecomment-213635717>
>



-- 
Jon Horton
Central Web Director
NewSpring Church
www.newspring.cc
Office: 864.965.9518
Cell: 919.218.6655
