### ISSUE TITLE
Weird issue

### ISSUE THREAD

**Issue by johnthepink** [NewSpring/Apollos#499]
I ran in to a weird issue today when building the `apollo-client` branch from scratch. Been trying to figure it out.

It seems that the branch at this point builds fine https://github.com/NewSpring/Apollos/commit/51e0db21aaf7fa1b31ad32aa3ec2bb7d7087beb4

But, progressing to this commit causes the server to not start at all. https://github.com/NewSpring/Apollos/commit/47f3b6b1f47f83c448533652266e3d4b4953759a

I imagine those string of commits I added while webpack was running, which is why I didn't see this before.

Investigating further.

**Comment by johnthepink** [comment]
Looks like it has to do with importing `apollo-client` at all. Just a basic:

```js
import ApolloClient from "apollo-client";
```

...fails to start the server. Wonder if it still has something to do with webpack loading apollos then loading apollo-client? I could have sworn I had this working.

**Comment by johnthepink** [comment]
Hmm. Tried including the package in like every possible place: apollos package.json, app webpack.packages.json, app package.json, symlinking, npm build, direct from github.

I'll try more tomorrow.

**Comment by johnthepink** [comment]
It seems there are some files that just do not want `apollo-client` imported in them. I think I'm getting around it though. Real funny stuff

- [x] **fix creation of ApolloClient**: *used separate file*
- [ ] **fix store integration**

**Comment by johnthepink** [comment]
let it be known that apollo-client does not like being imported in files with other imports, in our case anyways

**Comment by jbaxleyiii** [comment]
@johnthepink what the what? Crazy

**Comment by johnthepink** [comment]
@jbaxleyiii right? it gave no errors. just built everything and refused to start the server. i'm just so glad it's working now

**Comment by jbaxleyiii** [comment]
@johnthepink what did you do to get it working? 
<img width="565" alt="screen shot 2016-04-18 at 7 41 53 pm" src="https://cloud.githubusercontent.com/assets/4967600/14623178/b4a72328-059d-11e6-9fa4-9bcefe8fec8a.png">

**Comment by johnthepink** [comment]
@jbaxleyiii what are the errors above it?
