### ISSUE TITLE
ACH time of transaction

### ISSUE THREAD

**Issue by samclaridge** [NewSpring/Apollos#501]
As per a conversation with @benwiley yesterday, we need to ascertain how NMI is processing ACH transactions and why it takes so long.

### Main Issues
- Users don't know when to expect transactions to come out of their bank account, which results in a loss of trust in our new system.

- The above problem is compounded with scheduled gifts. Potentially waiting for over a week after you'd specifically defined the date you wanted is unacceptable.

### What We Currently Know
- ACH transaction is submitted via the give site, we receive confirmation and the token from NMI that the details were received. 

- NMI gives the transaction a sale date and it is deemed as unsettled until the transaction is successful, when it becomes settled.

- Rock does not import transactions until they are settled (although this feature is coming soon in an update).

- The user doesn't see the transaction post to their bank account until around 6 business days after they gave.

- The transaction posted to the users bank account never receives a pending status.

- The transaction in the users bank account is post-dated to a couple of days after sale date.

### Short-Term Solutions
- Over communicate to the user to expect a 6 business day delay on ACH.

- Display above message on the modal, scheduled page, and via email communications.

### Long-Term Options
- When Rock updates to import unsettled transactions, we can show pending gifts in the users giving history and send them email notifications. However, this doesn't solve the issue of it not showing in their bank statements, which is where the user would expect to see it.

- Find out from NMI how they are processing ACH. 
 - Why does it take so long to process?
 - Why does it never show a pending status in the user's bank account?
 - Why does it post-date transactions to dates that aren't the sale date?

- We could add another date field in Rock to ACH schedules to account for the delay and submit the transaction to NMI 3 business days early so the transaction shows up for the user closer to the correct time. I'm fully aware this is a hack and would break if NMI changed their system, and would also not fix one-time gifts. Hence the reason we need to find out why NMI are operating in the current manner.

**Comment by jbaxleyiii** [comment]
@samclaridge the new information we will have with the merge from Rock: (https://github.com/SparkDevNetwork/Rock/blob/develop/Rock.NMI/Gateway.cs#L716-L718)

```
payment.Status = // Pending, Failed, Success
payment.IsFailure = // true or false
payment.StatusMessage = // String of the response text (not user friendly words)
```

**Comment by samclaridge** [comment]
@jbaxleyiii agreed, that sounds like a good interim solution. I still think we need to reach out to NMI, because the practice of taking so long, not showing up as a pending transaction, and randomly post dating, seems shady and erodes the trust our users have in us.
