### ISSUE TITLE
[SENTRY] TypeError: undefined is not an object (evaluating 'this.store[o].networkStatus=t.NetworkStatus.ready')

### ISSUE THREAD

**Issue by conrad-vanl** [NewSpring/Apollos#522]
I believe this is an Apollo bug and I opened an issue here:
https://github.com/apollographql/apollo-client/issues/3345

---

https://sentry.io/newspring-church/apollos/issues/530406089/

```
TypeError: undefined is not an object (evaluating 'this.store[o].networkStatus=t.NetworkStatus.ready')
  at value ([native code])
  at forEach ([native code])
  at value ([native code])
  at value ([native code])
...
(25 additional frame(s) were not displayed)
```

**Comment by richarddubay** [comment]
@IsaacHardy See @conrad-vanl comment above. He created an issue for this on the Apollo Client repo ([3345](https://github.com/apollographql/apollo-client/issues/3345)) and he's also got a PR open to fix it (https://github.com/apollographql/apollo-client/pull/3367). Perhaps we should remove this from the sprint while we wait to see if the Apollo folks accept his PR?

**Comment by IsaacHardy** [comment]
That sounds good. Moving it to backlog.
