### ISSUE TITLE
[GraphQL error]: Message: unable to communicate with backend, Location: undefined, Path: undefined

### ISSUE THREAD

**Issue by IsaacHardy** [NewSpring/Apollos#536]
https://sentry.io/newspring-church/apollos/issues/528883937/

```
Stacktrace (most recent call first):

  at None (/Users/isaac.hardy/NewSpring/Apollos/src/@data/Client/errorLink.js:8:7)
  at forEach ([native code])
  at next (/Users/isaac.hardy/NewSpring/Apollos/src/@data/Client/errorLink.js:4:40)
  at value ([native code])
...
(12 additional frame(s) were not displayed)

[GraphQL error]: Message: unable to communicate with backend, Location: undefined, Path: undefined
```

**Comment by IsaacHardy** [comment]
@conrad-vanl Even with out Sentry breadcrumbs implemented, I'm still having a difficult time deciphering this error. 

It seems that this specific errors are purely a connection error to HL, but I cannot really test or reproduce it. This might be related to having a poor internet connection.

**Comment by conrad-vanl** [comment]
@IsaacHardy i believe this specific issue a generic catch all, you are correct. It is a connection error to HL. Sometimes when this error is logged, there was another error in sentry with more details logged at the same / similar time. For example, I think when we were hitting those search API errors, this 503 error was also triggered (I'm not certain, but that's just an example).

**Comment by IsaacHardy** [comment]
@conrad-vanl Would you say that might make this issue close worthy? I guess when I added this to the sprint, I suspected a larger issue. Not a generic connection catch all.

**Comment by conrad-vanl** [comment]
🤔 perhaps this issue could be changed to figure out how we can throw a more useful error, so we _don't_ have such a generic catch all?

Likely, that might mean investigating error handling in Heighliner itself.....

**Comment by IsaacHardy** [comment]
@conrad-vanl We could create a new issue for "Investigate error handling in Heighliner" and close this one.
