### ISSUE TITLE
Pending transactions aren't syncing properly from NMI

### ISSUE THREAD

**Issue by jonhorton** [NewSpring/Apollos#544]
I set up 2 scheduled transactions via ACH. One on 4/27 and the other on 5/1. As of today, they're still marked pending even though both have shown up in my bank account and cleared in NMI: 

History: https://www.dropbox.com/s/x77cmudjsvj6s7p/Screenshot%202016-05-08%2008.51.30.png?dl=0
NMI: https://www.dropbox.com/s/rpncm749s6xojl8/Screenshot%202016-05-08%2008.55.08.png?dl=0

If this is happening to me, it's likely happening to others. :(

**Comment by jbaxleyiii** [comment]
This appears to be an issue with the Rock NMI sync. I'm going to copy this over to the Rock repo and close out here
