### ISSUE TITLE
Music player text should respect light/dark switch

### ISSUE THREAD

**Issue by richarddubay** [NewSpring/Apollos#547]
## Acceptance Criteria

- [ ] As a NewSpring music connoisseur, I'd love it if the text on the music player was easy to read on all background colors, not just dark backgrounds.

## Context

Given that someone is using the music player when an album is loaded then the text in the player should switch between light and dark depending on a light/dark switch.

## UI Screenshot or Wireframe (optional)
![Screenshot 2018-04-29 11.56.16.png](https://images.zenhubusercontent.com/56156557638e718c995d9ed7/07bf8d4f-279c-4f66-9c30-ef7c68a5976b)
![Screenshot 2018-04-29 11.56.41.png](https://images.zenhubusercontent.com/56156557638e718c995d9ed7/b65c945b-7053-4c83-92a4-bd0a19f4daa1)

**Comment by burkeshartsis** [comment]
So this is why this is broken https://github.com/NewSpring/Apollos/blob/alpha/src/music/Player/FullScreenControls/index.js#L57
