### ISSUE TITLE
Investigate the Red Warning on ACH transactions that haven't settled yet.

### ISSUE THREAD

**Issue by FrankGrand** [NewSpring/Apollos#548]
## Acceptance Criteria

- [ ] Once the ACH transaction processed, the icon should go to green

## Context

Given [CONTEXT] when [ACTION] then [RESULT]

**Comment by IsaacHardy** [comment]
Could we have more information about this issue? Screen shots, context, etc.. @FrankGrand

**Comment by FrankGrand** [comment]
![download](https://user-images.githubusercontent.com/6911214/39410346-62ff5994-4bc5-11e8-9a1c-b56e6f4a8157.png)

**Comment by cdanwards** [comment]
@IsaacHardy Is there anyway to see what the 'status' of this is. I found where the decision about green/red icon is, but it's very explicit about what statuses make it green. I'm wondering if somehow the status is outside of the 4 listed, thus it is red.

**Comment by FrankGrand** [comment]
@cdanwards @IsaacHardy @conrad-vanl  Let's make sure there isn't a problem with ACH scheduled gifts.  In Rock, the only difference I see is that there isn't a reference number attached to the transactions like there are with the others.  Other difference is that in NMI there aren't any 'product details' like with other transactions.

**Comment by conrad-vanl** [comment]
@FrankGrand is your red transaction in the screenshot a scheduled ACH transaction, or a normal one?
