### ISSUE TITLE
TypeError: null is not an object (evaluating 'e.title')

### ISSUE THREAD

**Issue by IsaacHardy** [NewSpring/Apollos#549]
https://sentry.io/newspring-church/apollos/issues/539308490/

```
TypeError: null is not an object (evaluating 'e.title')
  at default (/Users/isaac.hardy/NewSpring/Apollos/src/@utils/content/share.js:6:16)
  at onPress (/Users/isaac.hardy/NewSpring/Apollos/src/@ui/SecondaryNav/index.js:12:12)
  at onPress (/Users/isaac.hardy/NewSpring/Apollos/src/@ui/NativeWebRouter/Link.js:59:20)
  at touchableHandlePress ([native code])
  at _performSideEffectsForTransition ([native code])
...
(23 additional frame(s) were not displayed)
```

**Comment by IsaacHardy** [comment]
This error stems from a lack of data. We need to address this possibility in Apollos.

**Comment by richarddubay** [comment]
@IsaacHardy @conrad-vanl From preliminary testing, it looks like I can consistently reproduce this error if I try to share something before all the content has loaded. The result is a restart of the app. I can add a check to make sure that there is something in `content.title` before trying to set it, but I feel like `content.name` could potentially have the same problem if the content truly isn't loaded yet. Perhaps a better solution would be to figure out how not to show the share and like nav while content is still loading? Thoughts?

**Comment by IsaacHardy** [comment]
I think your last option is the best. Perhaps displaying the icons if the `isLoading` boolean true? 

I would still want to test the UX of that change to make sure it still made sense. We can obviously do that in review.
