### ISSUE TITLE
[GraphQL error]: Message: User not authorized, Location: [object Object], Path: undefined

### ISSUE THREAD

**Issue by IsaacHardy** [NewSpring/Apollos#550]
https://sentry.io/newspring-church/apollos/issues/529069077/

```
Stacktrace (most recent call first):

  at None (/Users/isaac.hardy/NewSpring/Apollos/src/@data/Client/errorLink.js:8:7)
  at forEach ([native code])
  at next (/Users/isaac.hardy/NewSpring/Apollos/src/@data/Client/errorLink.js:4:40)
  at value ([native code])
...
(12 additional frame(s) were not displayed)

[GraphQL error]: Message: User not authorized, Location: [object Object], Path: undefined
```

**Comment by IsaacHardy** [comment]
Sentry issue: [APOLLOS-2N](https://sentry.io/newspring-church/apollos/issues/539303867/)

**Comment by IsaacHardy** [comment]
Sentry issue: [APOLLOS-1D](https://sentry.io/newspring-church/apollos/issues/529658221/)

**Comment by IsaacHardy** [comment]
@conrad-vanl @richarddubay @cdanwards This error seems to originate from an incorrect login combination. Do we agree that this is an error we can add to our ignore list within Sentry?

**Comment by IsaacHardy** [comment]
@conrad-vanl I am 99.98% sure. After the first hotfix today, I logged in with incorrect creds and this error came up. The language also suggests that it is due to an incorrect auth attempt.

**Comment by FrankGrand** [comment]
@IsaacHardy @conrad-vanl So I'm assuming that this issue should be opened back up??

**Comment by IsaacHardy** [comment]
@FrankGrand This issue revolves around an incorrect login, so I don't believe it is necessary.
