### ISSUE TITLE
Hookup metadata for groups :heart:

### ISSUE THREAD

**Issue by jonhorton** [NewSpring/Apollos#589]
Currently, when you share a group you see the default metadata instead of what's related to the group https://www.dropbox.com/s/ijd8j39jet5h266/Screenshot%202016-06-06%2011.12.51.png?dl=0

Let's hook up 
* the group title as the page title
* First 140 chars of the description as the meta description
* Group photo as the meta image (use default if one doesn't exist) (Include for Fb tags along with twitter tags.

**Comment by jbaxleyiii** [comment]
done!
