### ISSUE TITLE
Need a more accessible and scalable way to display repeat one and repeat all

### ISSUE THREAD

**Issue by samclaridge** [NewSpring/Apollos#605]
Currently the repeat cycle is displayed by changing from the primary color, either light or dark, and then to green primary. This present form is hard to see as a user as the contrast change is so subtle (this will be exacerbated on screens at lower light or with lesser quality screens). It is also unclear which color change is toggling which version of the repeat.
 
@jbaxleyiii proposed solution is to add a callout:

Using one instead of 1 so they occupy the same visual space.
Right of the icon instead of above/below because of our limited height on small screens.
We can add these to our ico-font, with the text being knocked out of the object, so the text always takes on the album color.

![player-dark-repeat-all](https://cloud.githubusercontent.com/assets/7452283/15911106/31ad92dc-2d9c-11e6-8912-c71439d5ae2a.png)
![player-dark-repeat-one](https://cloud.githubusercontent.com/assets/7452283/15911107/31affea0-2d9c-11e6-842b-27edc3ef9602.png)
![player-light-repeat-all](https://cloud.githubusercontent.com/assets/7452283/15911109/31b21884-2d9c-11e6-8627-65d29bdcf77a.png)
![player-light-repeat-one](https://cloud.githubusercontent.com/assets/7452283/15911108/31b0a364-2d9c-11e6-98ee-b91c61d91bb4.png)

**Comment by johnthepink** [comment]
@samclaridge you were working on this right? I'll assign it to you.

**Comment by samclaridge** [comment]
@johnthepink yeah it’s done, it’ll be in the Music Player branch when it
gets merged in, but I’m still working on some other UI tweaks.

**Comment by johnthepink** [comment]
Closed by #661
