### ISSUE TITLE
Modal nav doesn't close when modal is closed

### ISSUE THREAD

**Issue by jonhorton** [NewSpring/Apollos#613]
**Steps to reproduce**
- From the home feed, view an entry (devo)
- While signed out, tap the favorite icon
- Close the modal (x) without signing in

**Buggy behavior**
- Modal screen closes, but the X icon stays present
- tapping the X icon no longer responds, and it's not possible to go back to the previous screen

**Comment by johnthepink** [comment]
Fixed by #611
