### ISSUE TITLE
Increase tap area on nav elements

### ISSUE THREAD

**Issue by jonhorton** [NewSpring/Apollos#614]
Sometimes when attempting to tap a nav item, it doesn't respond. It appears that this happens because the tappable area for nav items doesn't fill the entire space available in the nav bar.

Does this make sense?

I can see the area visually on android which more clearly illustrates the issue!

**Comment by johnthepink** [comment]
Do you think this is Android specific? The tap targets seem to pretty well fill the space (see below). There is however, a separate issue that I've encountered sporadically that I can't reproduce where the nav doesn't respond. 

<img width="550" alt="screenshot 2016-06-14 19 04 12" src="https://cloud.githubusercontent.com/assets/816517/16062705/f49bccee-3262-11e6-82f2-171638517e96.png">

**Comment by johnthepink** [comment]
^^ all of the blue and green trigger the back action

**Comment by jonhorton** [comment]
I think what I may be seeing is that sometimes (maybe 30% of the time) I end up tapping the 5-10px space above that area—the gray section within the nav— which results in either nothing happening, or sometimes tapping a link on the active page.

It's possible that I'm the only one that's experienced that issue. Have you had that happen?

**Comment by johnthepink** [comment]
@jonhorton i think we should probably expand them to the top and the bottom. i was looking at the space on the bottom, and didn't notice the space on the top is larger. it shall be done.

**Comment by jonhorton** [comment]
thanks @johnthepink!
