### ISSUE TITLE
Can't scroll within discover results

### ISSUE THREAD

**Issue by jonhorton** [NewSpring/Apollos#616]
Steps to Reproduce
- Tap the Discover section
- Search for a keyword
- Attempt to scroll through results

Buggy Behavior
- It's not possible to scroll, even though results exist (visibly cut off by the screen)

**Comment by johnthepink** [comment]
@jonhorton I just tried to reproduce this, and it seems to be scrolling for me. However, it is wonky in general. @jbaxleyiii I think we need to find a way to move sections and discover out of the modal in the app. When I scroll with the keyboard still open, the content behind it starts appearing.
