### ISSUE TITLE
Increase threshold for number of items lazy load fetches

### ISSUE THREAD

**Issue by jonhorton** [NewSpring/Apollos#617]
Currently, when scrolling through the feed, you often have several seconds of delay when viewing a new card while the lazy load plugin loads the image.

I propose that we increase the number of items the plugin looks ahead to fetch to something like 3 or 4 items past the card in view, so that scrolling through the feed feels like there's no delay and more responsive. Speed++

**Comment by johnthepink** [comment]
@jbaxleyiii do you have time to look at this? I think you understand the logic better than me at this point. If not, I'll figure it out.
