### ISSUE TITLE
Group Finder map markers do not match brand

### ISSUE THREAD

**Issue by briankalwat** [NewSpring/Apollos#628]
## Acceptance Criteria

- [ ] Map markers in group finder should match the tertiary/primary (active) brand color markers currently in my.newspring.cc

## Context

When searching for a group in group finder, the map markers are not on-brand.

## UI Screenshot or Wireframe (optional)

![image](https://user-images.githubusercontent.com/2465823/40186799-f8b7d3ba-59c3-11e8-86c9-e7d2472853c3.png)

![image](https://user-images.githubusercontent.com/2465823/40186815-02bd4fca-59c4-11e8-8fb4-a339cbbcaffc.png)

**Comment by conrad-vanl** [comment]
Unfortunately this is not currently supported in the react-native-web mapview
