### ISSUE TITLE
Music Player Updates

### ISSUE THREAD

**Issue by johnthepink** [NewSpring/Apollos#628]
via https://github.com/NewSpring/newspring-app/issues/186

**Comment by johnthepink** [comment]
@samclaridge @jbaxleyiii I think we have made most of these updates, but I'll leave this open until the newest changes get merged

**Comment by delianides** [comment]
FWIW the artist titles on all the albums are incorrect. It should be "NewSpring Worship" for any of our worship albums and Lee's album, coincidentally, should be "Lee McDerment"

**Comment by johnthepink** [comment]
@delianides yep! Last time I checked, we needed to add artist information in EE so we can set it dynamically.
