### ISSUE TITLE
Capitalization should not be forced on group names

### ISSUE THREAD

**Issue by briankalwat** [NewSpring/Apollos#629]
## Acceptance Criteria

- [ ] Capitalization should not be forced on group names for group leader toolbox.

## UI Screenshot or Wireframe (optional)

![image](https://user-images.githubusercontent.com/2465823/40186963-59dcc696-59c4-11e8-994c-70380086326b.png)

**Comment by conrad-vanl** [comment]
Easy fix, whoever wants to take it: https://github.com/NewSpring/Apollos/blob/alpha/src/%40ui/ThumbnailCard/index.js#L63

**Comment by richarddubay** [comment]
I'll take it.

**Comment by richarddubay** [comment]
@burkeshartsis Yep. I know you made an issue to go back through and audit that (#580). Do you feel like we need to do that right now? Or just fix this one and then do the audit?
