### ISSUE TITLE
NewSpring Logo went to CrossFit

### ISSUE THREAD

**Issue by johnthepink** [NewSpring/Apollos#629]
via https://github.com/NewSpring/newspring-app/issues/165

**Comment by johnthepink** [comment]
possibly fixed by #709

**Comment by johnthepink** [comment]
@benwiley @dcs619 confirmed fixed

**Comment by benwiley** [comment]
I did?

**Comment by dcs619** [comment]
@johnthepink *turns the lights out*

![](https://media.giphy.com/media/bQTNe9xrF6D6M/giphy.gif)
