### ISSUE TITLE
Side cards at bottom of Group Finder should use meta serif for body copy

### ISSUE THREAD

**Issue by briankalwat** [NewSpring/Apollos#630]
## Acceptance Criteria

- [ ] Side cards at bottom of Group Finder should use meta serif for body copy

## UI Screenshot or Wireframe (optional)
https://my.newspring.cc/groups/home
![image](https://user-images.githubusercontent.com/2465823/40187347-518fec24-59c5-11e8-88a6-e4bf3ad7af25.png)

https://beta.apollos.newspring.cc/groups
![image](https://user-images.githubusercontent.com/2465823/40187468-94ba5336-59c5-11e8-9657-b536573af97d.png)

**Comment by richarddubay** [comment]
We use meta (or something like it) on the GroupCard. I feel like these cards here are just missing `<BodyText>` maybe?

**Comment by conrad-vanl** [comment]
@richarddubay I believe so. Should be an easy fix if so

**Comment by richarddubay** [comment]
@conrad-vanl I can take a look at it if you'd like.
