### ISSUE TITLE
Group Finder Member Lists should not show pending members

### ISSUE THREAD

**Issue by richarddubay** [NewSpring/Apollos#631]
## Acceptance Criteria

- [ ] It should not show pending members

## Context

Given that a person is viewing a groups details when they see the members then they should only see actual approved members of the group and not pending members. This is current functionality on Holtzman.

## UI Screenshot or Wireframe (optional)
On Holtzman:
![Screenshot 2018-05-17 11.38.45.png](https://images.zenhubusercontent.com/56156557638e718c995d9ed7/81abd637-7b62-4594-b3ec-ac73dfde606e)
On Apollos:
![Screenshot 2018-05-17 11.39.00.png](https://images.zenhubusercontent.com/56156557638e718c995d9ed7/7b645889-4beb-48e0-aee7-045f66028fc5)

**Comment by conrad-vanl** [comment]
Weird. I swear a copied and pasted the same user filtering logic from Holtzman. Guess I missed something... 😭
