### ISSUE TITLE
Group location distance not correct

### ISSUE THREAD

**Issue by richarddubay** [NewSpring/Apollos#632]
## Acceptance Criteria

- [ ] It should tell me the distance the group is from me.

## Context

Given that I'm looking for a group when I see the results then it should show me how far away that group is.

## UI Screenshot or Wireframe (optional)
![Screenshot 2018-05-17 11.52.50.png](https://images.zenhubusercontent.com/56156557638e718c995d9ed7/1e71c538-7396-460d-8668-99900bea027d)

**Comment by conrad-vanl** [comment]
Weird...I'm seeing the correct distance (everything is like 800 miles plus away from me 😭). Did you tell the search form to "Use your location"?  I think we are only able to estimate that if we know the user's current location. Maybe we can disable that line of text if we don't have their location.

**Comment by richarddubay** [comment]
@conrad-vanl I just tried it again to be sure. When "Near my Location" is turned on, I get 0 miles as the distance. Funny enough, if I turn that off and put in my zip code then I get results with actual distances. 

And yeah, I do think that if the results come back as 0 that we should disable that line. It's not helpful for anyone at that point.

**Comment by conrad-vanl** [comment]
weird. Okay i'lll look into it. It's definitely working both ways for me. What browser/environment are you testing in?

**Comment by richarddubay** [comment]
I'm using Chrome and I'm testing on beta.apollos.newspring.cc. I can try some other browsers too.

**Comment by richarddubay** [comment]
So the solution could be to not round the miles, that way it matches what we have in Holtzman.

**Comment by conrad-vanl** [comment]
AHH!!!

**Comment by conrad-vanl** [comment]
Do you want to make that change? Happy to if not: https://github.com/NewSpring/Apollos/blob/alpha/src/group-finder/GroupCard.js#L91

**Comment by richarddubay** [comment]
Yep. I'll take it.
