### ISSUE TITLE
Safari: Some text not showing correct font

### ISSUE THREAD

**Issue by conrad-vanl** [NewSpring/Apollos#636]
On Safari, some text is using system default serif font:

![image](https://user-images.githubusercontent.com/103927/40190909-9fdf44f6-59c5-11e8-9788-a36b1359ff34.png)

**Comment by conrad-vanl** [comment]
Looks like it might be all italicized text

**Comment by burkeshartsis** [comment]
I've looked into this and I don't know why it's not working. Going to punt this for now as the fix is not as obvious as it would seem.
