### ISSUE TITLE
Edge: Unable to login to Edge

### ISSUE THREAD

**Issue by IsaacHardy** [NewSpring/Apollos#639]
## Acceptance Criteria

- [ ] A user should be able to successfully login to their account when using Edge as their browser.

**Comment by conrad-vanl** [comment]
@IsaacHardy could you try to post some debugging info on this issue? Perhaps an error console or anything like that? I won't be able to look at this myself on Edge until later today or tomorrow morning, but might be able to tell whats going on with a little context.

**Comment by IsaacHardy** [comment]
@conrad-vanl Aboslutely. I'm gonna grab our PC test machine here in a bit and grab some more details on this issue.

**Comment by IsaacHardy** [comment]
The best I can come up with, is that the call tot he server to login an individual is never resolving and just continues to display the `isLoading` component permanently. They are signs when you first click the "Go" button to login that you are login and your profile is about to be loaded, but then it takes a turn and just never loads. You can try going to another place in the web app but it will redirect you to the login screen.
