### ISSUE TITLE
Status bar disappears on Series

### ISSUE THREAD

**Issue by delianides** [NewSpring/Apollos#653]
![img_0572](https://cloud.githubusercontent.com/assets/111170/16094293/9026392e-330d-11e6-8125-2449f58e5f7e.PNG)

**Comment by johnthepink** [comment]
@drew i think this happens after viewing a video. Because the status bar goes black when the video goes full screen. We should add an event after video exit to reset the header

**Comment by johnthepink** [comment]
@delianides i think this happens after viewing a video. Because the status bar goes black when the video goes full screen. We should add an event after video exit to reset the header

**Comment by delianides** [comment]
@johnthepink is it worth a conversation to have the same color for the status bar across the whole app? when the phone is plugged in the green icon for the battery looks weird against newspring green. NS black would look better I think.

**Comment by johnthepink** [comment]
@delianides that would be a question for @samclaridge. We are currently changing the status bar color when you get to a Series with a collection color. And I think the point of having the status bar green is so it looks like one large green header, and one large color of whatever the series collection color is on the series screen.

**Comment by samclaridge** [comment]
@delianides yeah the default behavior on iOS is for the status bar to mirror the color of the header bar to feel like one seamless piece of the interface. This is also the reason it matches the changing header color of the series brand.
