### ISSUE TITLE
Pull to Refresh Display Issues

### ISSUE THREAD

**Issue by delianides** [NewSpring/Apollos#654]
![img_0574](https://cloud.githubusercontent.com/assets/111170/16094367/f23a3ec6-330d-11e6-8d1c-43b4b9e626e0.PNG)

- [x] Strange white overlay when PTR is activated
- [x] Drop isn't centered

**Comment by johnthepink** [comment]
Yep! On my.newspring.cc we are using the overlay as a hover state, but we should probably disable it in the app.

**Comment by delianides** [comment]
@johnthepink you this fixed the issue with the alignment and the overlay but now the drop is visible during the page load when PTR isn't activated.

**Comment by johnthepink** [comment]
@delianides it was like that before. We need a separate issue for overriding the image loader opacity for the hero component.

**Comment by johnthepink** [comment]
https://github.com/NewSpring/Apollos/issues/674
