### ISSUE TITLE
Can't scroll on feed pages

### ISSUE THREAD

**Issue by jbaxleyiii** [NewSpring/Apollos#666]
Loading any feed (home, articles, sermons, etc) will load content, but I can't scroll down at all

**Comment by johnthepink** [comment]
Do you have reproduction steps? Everything seems to be scrolling for me.

**Comment by johnthepink** [comment]
The issue is reproducible on iOS 9.2.1, but seems to have been fixed between there and 9.3.2. We should investigate where in there it was fixed, and how we can support versions where it is broken.

**Comment by johnthepink** [comment]
iOS 9.2 may have the same issue, via feedback from another user.

**Comment by johnthepink** [comment]
@jbaxleyiii said he fixed this issue, and I am forever grateful
