### ISSUE TITLE
Video ratio for sermons is slightly off

### ISSUE THREAD

**Issue by jonhorton** [NewSpring/Apollos#675]
When viewing a sermon, it appears that the ratio is slightly off. The best way to tell, is by viewing a worship segment when the lyrics on on the bottom left of the screen. The second line is always cut off, even when the scrubber disappears.

There are also some potential issues on android with the video player controls, due to how android handles video vs ios. (I'll file another bug for that!)

**Comment by johnthepink** [comment]
@jonhorton it sounds like you found this on Android. Is that true?

**Comment by jonhorton** [comment]
@johnthepink Found on android, but I believe it still exists on iOS—it's just masked by the fact that the iOS auto full screens the video.  I believe the video container itself is still the wrong ratio.

**Comment by johnthepink** [comment]
@jonhorton ok awesome. I'll check it out :)

**Comment by johnthepink** [comment]
Hopefully, the fix is in #707, but I'll leave this open for now.

**Comment by delianides** [comment]
@jonhorton @johnthepink I actually think this would fix #692 too with the exception of integrating chromecast but that should be a separately tracked issue because its more involved than just "adding a chromecast icon" 😉

**Comment by jonhorton** [comment]
@delianides @johnthepink yay! I agree, it looks like this fixed #692 as well. 👍 

Thanks for adding the Chromecast Issue Drew!

**Comment by johnthepink** [comment]
Great! I'll close them both.
