### ISSUE TITLE
Devotional Swiping to Verses is Janky

### ISSUE THREAD

**Issue by delianides** [NewSpring/Apollos#677]
Devo swiping to verses is too sensitive.

**Comment by johnthepink** [comment]
I worked on this once, and couldn't figure out bringing down the sensitivity without forcing you to do a much larger swipe. So, eventually I just turned off swiping. It may be worth going back to that for now, and then come up with a better solution later.

**Comment by johnthepink** [comment]
per convo. let's go with disabling for now.

**Comment by johnthepink** [comment]
Fixed via https://github.com/NewSpring/react-swipe-views/commit/03061c165ee3760e6d8084a2e19bd90d00b4f27b
