### ISSUE TITLE
Video player freezes frame after ~4 minutes

### ISSUE THREAD

**Issue by jonhorton** [NewSpring/Apollos#691]
This was tested on Android (currently testing ios)

**Steps to reproduce**
- Pick a sermon and begin playing.
- Wait 4–5 minutes
- I've been able to reproduce 3 times between 4:10 and 4:30 minute mark

**Buggy Behavior**
- Frame will freeze and sometimes stutter between 1 or 2 frames while the audio continues playing
- pausing / playing will stop audio but not reset video
- Scrubbing also has no effect
- Further weirdness happens on pause/replay

**Comment by jonhorton** [comment]
Just for information—tested this again with the new builds and it still exists.

**Comment by johnthepink** [comment]
Thanks for the heads up @jonhorton. I think I mentioned to some people, but let's rebase our ooyala player fork and see what that gets us.

**Comment by johnthepink** [comment]
@jonhorton I think this is fixed. We included an updated video player, and I haven't been able to reproduce the issue now. Closing for now.
