### ISSUE TITLE
Video player bugs

### ISSUE THREAD

**Issue by jonhorton** [NewSpring/Apollos#692]
On Android, when viewing a video there are a few polish issues

* When clicking play, a stretched, white image with a play button is displayed while the video content loads. Maybe this could be a loading icon instead? Or at the very least black.
* After playing a video, the only controls available are the scrub bar. A pause/play button, full screen icon would be helpful at the least. Next level would be the addition of a chromecast icon.

**Comment by johnthepink** [comment]
Closed in favor of #715
