### ISSUE TITLE
Update devotions to devotionals

### ISSUE THREAD

**Issue by jonhorton** [NewSpring/Apollos#697]
We currently use the word devotionals instead of devotions. Let's update this across the app for consistency! 

It looks like it's only showing up incorrect in the Profile > Following section > In the list.

**Comment by johnthepink** [comment]
This is here https://github.com/newspring/apollos/blob/master/apollos/profile/blocks/following/index.jsx

But, this won't be as simple as just changing the text. "Devotions" in the topics array is used to display the "Devotions" text next to the switch, but is also used to filter out the home feed. So may also be an update to heighliner involved
