### ISSUE TITLE
Missing content type icon under Profile > Likes

### ISSUE THREAD

**Issue by jonhorton** [NewSpring/Apollos#699]
All other cards within the app have a fun little icon next to the content type. It appears to be missing within cards under the Profile > Likes cards.

**Steps to Reproduce**
- Visit the Profile section
- Observe a card under the Likes section (Tested with liked content—not the default cards)

**Buggy Behavior**
- Icon is missing next to the content type (Articles, Devotionals, Sermons, etc)

**Comment by johnthepink** [comment]
I think we should also add the capitalization we added to titles in other places for the liked items. See https://github.com/NewSpring/Apollos/pull/648

**Comment by jonhorton** [comment]
Good catch—I agree! Consistency++
