### ISSUE TITLE
Ensure Google Analytics On for Alpha and Beta

### ISSUE THREAD

**Issue by johnthepink** [NewSpring/Apollos#700]

**Comment by jonhorton** [comment]
The token for beta + production is UA-7130289-24

**Comment by jonhorton** [comment]
The token for the alpha app is UA-7130289-32

**Comment by johnthepink** [comment]
Fixed in https://github.com/NewSpring/ops-settings/commit/1364c605d3c9dd20347fc92dcc182921594f5ed4
