### ISSUE TITLE
Full Player loses all data from Devotional

### ISSUE THREAD

**Issue by samclaridge** [NewSpring/Apollos#714]
When trying to view the Full Player from a Devotional there is no data in the modal, only a blank screen with the down arrow.

Steps to reproduce:

1. Navigate to an album and start playing a song.
2. Go to the feed, tap on an a devotional.
3. Tap on the Mini Player.
4. Full Player is blank with only the down arrow.

This is happening on my device with the current build, the simulator, and the web.

**Comment by jbaxleyiii** [comment]
@samclaridge confirmed on android

**Comment by johnthepink** [comment]
Does not predate the monolith https://github.com/NewSpring/Apollos/commit/d208e48f7fe43f390d82c4b9620768d91a4e8e3a

Goes back as far as 2e85184

**Comment by johnthepink** [comment]
Looks to have something to do with the header. Possibly in this PR https://github.com/NewSpring/Apollos/pull/610
