### ISSUE TITLE
Font on series/sermon cards is fuzzy on iOS

### ISSUE THREAD

**Issue by jonhorton** [NewSpring/Apollos#719]
**Steps to reproduce** (Tested on iPhone 6 Plus)
- Open app and view a sermon card either in the feed or from a section
- Observe the sermon title, content type, and date

**Buggy Behavior**
- Fonts for all text areas in this card type are fuzzy/aliased

**Comment by johnthepink** [comment]
You're right. That's interesting.

**Comment by johnthepink** [comment]
@jonhorton I think this is fixed. I don't see it anymore. Feel free to re-open if you still have it.
