### ISSUE TITLE
Album cards are missing images on the home feed 

### ISSUE THREAD

**Issue by jbaxleyiii** [NewSpring/Apollos#724]
Steps to reproduce:

1. Filter home feed down to just albums
2. Go to the home feed

(Also, albums without content show up)

**Comment by jonhorton** [comment]
I was _just_ about to publish this bug too! 
![screenshot_20160622-220749](https://cloud.githubusercontent.com/assets/619297/16289824/7c2fa7a2-38c6-11e6-829b-eaf20900a2c8.png)

**Comment by johnthepink** [comment]
Good catch. I would guess this is on the Heighliner side of things

**Comment by johnthepink** [comment]
Fixed via #notsure

![screenshot 2016-08-23 10 44 57](https://cloud.githubusercontent.com/assets/816517/17896619/4ed39ef6-691f-11e6-865e-f8115e7a29b6.png)
