### ISSUE TITLE
Onboarding styles

### ISSUE THREAD

**Issue by johnthepink** [NewSpring/Apollos#746]
I don't think this looks like it used to, padding-wise

![localhost-3000- iphone 6 plus](https://cloud.githubusercontent.com/assets/816517/16620345/182f2238-4360-11e6-8391-dfffbbd23560.png)

**Comment by samclaridge** [comment]
@johnthepink is that the 6 Plus?

**Comment by johnthepink** [comment]
@samclaridge yep

**Comment by jbaxleyiii** [comment]
fixed
