### ISSUE TITLE
Music player overlay color

### ISSUE THREAD

**Issue by johnthepink** [NewSpring/Apollos#759]
Right now it's always black. We should bring back the collection color. Not sure if it's not making it from Heighliner, or if we are just referencing it incorrectly.

![screenshot 2016-07-06 15 52 04](https://cloud.githubusercontent.com/assets/816517/16632325/9cde2692-4391-11e6-8fe7-9d2afdb101e1.png)

**Comment by jbaxleyiii** [comment]
This looks like a highliner bug

**Comment by jbaxleyiii** [comment]
fixed in next heighliner release
