### ISSUE TITLE
Group Finder map markers disappear when loading additional results

### ISSUE THREAD

**Issue by jonhorton** [NewSpring/Apollos#778]
**Steps to Reproduce**
* Select tags to search in Group Finder
* scroll to the bottom and click more results

**Buggy Behavior**
* All map markers disappear: [Screenshot](https://www.dropbox.com/s/cqk54am04tqyd5q/Screenshot%202016-07-17%2009.19.40.png?dl=0)

**Expected behavior**
* Map markers update to show all markers, including new ones

**Comment by jbaxleyiii** [comment]
@jonhorton on it!

**Comment by jbaxleyiii** [comment]
Fixed in next build
