### ISSUE TITLE
Beta App is not pulling the latest stories

### ISSUE THREAD

**Issue by jonhorton** [NewSpring/Apollos#783]
If you view stories in the [beta app](https://beta-native.newspring.cc/stories) (or [alpha app](https://alpha-app.newspring.io/stories)), it's not pulling the latest ones available at [https://newspring.cc/stories](https://newspring.cc/stories). The most recent one in the app is Mary Ashleigh's story.

I've also checked dates on the most recent stories, and they're all recent.

Perhaps it's a caching or Heighliner issue?

**Comment by jbaxleyiii** [comment]
@jonhorton this looks like a heighliner issue! I'll investigate

**Comment by jbaxleyiii** [comment]
@jonhorton this was because we were only pulling `open` status and not `open || featured`. Fixed in the next heighliner deploy (next 20 mins or so)
