### ISSUE TITLE
Removing tags from the search bar doesn't unselect them from the list

### ISSUE THREAD

**Issue by jonhorton** [NewSpring/Apollos#797]
[Screenshot](https://www.dropbox.com/s/fz2clyvn8o5wgyj/Screenshot%202016-07-18%2014.29.15.png?dl=0)

Steps to Reproduce
- search for 4 tags
- remove a tag from the search bar

Buggy behavior
- The expanded list of tags still shows the removed tags selected

Expected Behavior
- Removed tags are unselected from both the search bar + the full list.

**Comment by jbaxleyiii** [comment]
Fixed in next build
