### ISSUE TITLE
Unselecting a tag from the search bar, unhighlights the next one

### ISSUE THREAD

**Issue by jonhorton** [NewSpring/Apollos#798]
[Screenshot](https://www.dropbox.com/s/lee5da6hzf4j8ms/Screenshot%202016-07-18%2014.32.09.png?dl=0)

Steps to Reproduce
- Search for 3 tags
- In the search bar, remove a tag
- Observe

Buggy Behavior
- The tag is removed properly, but the active state of the next tag is removed (it turns gray)

Expected Behavior
- Only the tag removed should be affected
- The next tag should retain the active state.

**Comment by jbaxleyiii** [comment]
Fixed in next build
