### ISSUE TITLE
Decide pattern for styling and theming components

### ISSUE THREAD

**Issue by conrad-vanl** [NewSpring/Apollos#8]
Lets figure out how we want to style and provide theming support for components.

We've talked about using `styled-components`, using a `styled` HOC, and/or a `provider` component for theming....among other open source solutions.

We can use this issue to document ideas.

## Acceptance Criteria

- [ ] Initial style implementation in code, with documentation on our plan

**Comment by conrad-vanl** [comment]
Sloppy code for what a `styled` HOC could look like:

```javascript
import { withProps } from 'recompose';
const styled = getStyle => withProps(props => ({
  style: [
    getStyle(props),
    props.style || {}, 
  ],
}));

// Usage in a component:
const Button = styled(props => ({
  borderRadius: 3,
  padding: 50,
  margin: 10,
  width: ‘100%’,
  background: ‘transparent’,
  color: ‘white’,
  ...props.primary ? {
     background: ’white’,
     color: ’palevioletred’,
  } : {},
}))(View);
```

Could do some further work, such as being able to pass in `StyleSheet` styles from `ReactNative`, better array support / flattening, etc.

**Comment by Lepozepo** [comment]
Not too sure what more we can contribute here but it looks like we have theming down at least through #17. I looked at styled components and how we could use it in our frame but I think having styled components work with react-native-web is going to be problematic. What other patterns were you guys thinking about?

**Comment by conrad-vanl** [comment]
@Lepozepo I will probably close this soon. I just haven't had time between context switching to think about it. If it's closed it'll go off my radar :)

So can we leave this open for now, and we can move on but you can remove yourself as an assignee if you want. I think I agree with you and we're likely good.
