### ISSUE TITLE
Giving history card should use NickName instead of FirstName

### ISSUE THREAD

**Issue by jonhorton** [NewSpring/Apollos#804]
Steps to Reproduce
- Visit the giving history page
- Note the name listed on the card

Buggy Behavior
- First name should use NickName if available

[Screenshot](https://www.dropbox.com/s/ltvj2j3n0tbx0d3/Screenshot%202016-07-24%2009.08.21.png?dl=0)

**Comment by jbaxleyiii** [comment]
will be fixed in a build today!
