### ISSUE TITLE
Loading more results for giving history with a filter selected doesn't work on first click

### ISSUE THREAD

**Issue by jonhorton** [NewSpring/Apollos#806]
Steps to Reproduce
- Visit the giving history page
- Configure a filter (I used 01/16 + 01/15 as a start date)
- scroll to the bottom and click the Load more results button.

Buggy Behavior
- When the button is clicked, the page scrolls to the top and fails to actually load more results.
- Clicking a second time appears to work.

Expected behavior
- Results are loaded immediate without having to scroll back down.

Improvement: Since a user is already setting a filter, would it make sense to just show all results that the filter returns? BUT if a filter isn't set, then use the load more action?

**Comment by jbaxleyiii** [comment]
@jonhorton I'll see what the response time is with loading all results

**Comment by jbaxleyiii** [comment]
@jonhorton I' haven't been able to replicate this?

**Comment by jonhorton** [comment]
@jbaxleyiii I can consistently replicate by configure the following filters
- At least one person is selected
- Set a start date without an end date
- Allow the initial filtering to complete
- Scroll down and click the load more button

[Screenshot](https://www.dropbox.com/s/uvbqkken50xe8wl/Screenshot%202016-07-24%2012.19.17.png?dl=0)

All subsequent clicks work.
Does that still not replicate for you?

**Comment by jbaxleyiii** [comment]
@jonhorton bizarre, it works great for me following those replication steps...

**Comment by jonhorton** [comment]
@jbaxleyiii so weird! Perhaps someone else can test/verify? 
cc: @meredithrouse @samclaridge @johnthepink?

**Comment by johnthepink** [comment]
@jonhorton I can't produce it either
