### ISSUE TITLE
Completed schedule doesn't show related transactions while in pending status

### ISSUE THREAD

**Issue by jonhorton** [NewSpring/Apollos#807]
[Screenshot](https://www.dropbox.com/s/rj3dt87t1iidymc/Screenshot%202016-07-24%2009.21.51.png?dl=0)

Steps to reproduce
- Create a schedule
- View schedule history on day of the scheduled transaction

Buggy Behavior
- While the transaction is pending, there is conflicting information. The schedule history shows that the schedule is completed. The giving history shows the scheduled transaction.
- However, when viewing the schedule, it says there are no related transactions. Most likely because it's still pending.

**Comment by jbaxleyiii** [comment]
@jonhorton I ran into this as well! I'll take a look!

**Comment by jbaxleyiii** [comment]
fixed in next build
