### ISSUE TITLE
Use more descriptive text when no group results are found

### ISSUE THREAD

**Issue by jonhorton** [NewSpring/Apollos#808]
Steps to Reproduce
- Visit group finder and search for [something that has no results](https://my.newspring.cc/groups/finder?q=homebrew)
- Observe

Buggy Behavior
- Load more button shouldn't be present when no results are found

Expected Behavior
- Button is not present
- Text exists saying that no groups were found

**Comment by jbaxleyiii** [comment]
added to the next build
