### ISSUE TITLE
Clicking/Tapping Groups from the main nav should go to the group finder home page

### ISSUE THREAD

**Issue by jonhorton** [NewSpring/Apollos#809]
Steps to reproduce
- Visit [group finder and search for a group](https://my.newspring.cc/groups/finder?tags=kid+friendly%2Ccoed)
- Click on the Groups main nav item

Buggy Behavior
- User is not redirected to /groups/finder
- Nothing happens

Expected Behavior
- The /group/finder landing page loads and resets currently selected options

**Comment by jbaxleyiii** [comment]
fixed in next build
