### ISSUE TITLE
Load more groups button doesn't load more groups

### ISSUE THREAD

**Issue by jonhorton** [NewSpring/Apollos#810]
Steps to Reproduce
- Visit group finder and search for a group
- Scroll to the bottom and click the load more button
- Observe

Buggy Behavior
- Results aren't loaded regardless of how many times the button is pressed.

[Screenshot](https://www.dropbox.com/s/npzta2nw1968bgo/Screenshot%202016-07-24%2009.54.42.png?dl=0) [Link](https://my.newspring.cc/groups/finder?tags=married%2Chobbies&utm_campaign=Group+Finder&utm_medium=promo&utm_source=my.newspring.cc)

**Comment by samclaridge** [comment]
Interesting, the Load More btn is working on Beta.
