### ISSUE TITLE
Add additional link spots on cards on Group Finder

### ISSUE THREAD

**Issue by jonhorton** [NewSpring/Apollos#811]
Steps to Reproduce
- Visit group finder and scroll down to the articles
- Try clicking on the image

Buggy behavior 
- Image isn't clickable (inconsistent with campaign cards on give.)

**Enhancement**
- I'd love us to consider linking the titles. Is there a reason we haven't done that on these cards?

**Comment by jbaxleyiii** [comment]
fixed in next build, the entire card (including title) will be clickable
