### ISSUE TITLE
Group Finder search behaves differently when searching multiple criteria

### ISSUE THREAD

**Issue by jonhorton** [NewSpring/Apollos#812]
According to the search description, you can search by name, campus, zip code, and keyword. I'm noticing some inconsistencies when searching for multiple keywords.

**Singles**
Returns results where the word singles appears, including a greenville singles group.

**Greenville** 
Returns results that are located in Greenville.

**[Greenville Singles](https://my.newspring.cc/groups/finder?q=greenville+singles)**
Returns no results

I would expect the greenville singles to at the very least return the [singles group](https://my.newspring.cc/groups/85e7fcbe71e3a9cbda53cd0343708d86) that is located in Greenville.

My theory is that the search query isn't looking at all of those fields for matches when multiple keywords are present, and instead, it's look at just text fields.

Any ideas?

**Comment by jbaxleyiii** [comment]
@jonhorton the only thing that I could thing of would be to split each query into a separate query and search all words together. So `greenville singles` would search `greenville`, and `singles` instead of `greenville singles`

**Comment by johnthepink** [comment]
@jbaxleyiii would it be possible to do an OR in the query? so `greenville || singles`? or maybe `(greenville && singles) || greenville || singles`

**Comment by jonhorton** [comment]
@jbaxleyiii @johnthepink I think it would be worth it even though the query may be expensive. Right now people would be missing out on a large number of groups when searching this way!

Should we begin to think/talk through indexing content in a better way so that we could use elastisearch or something similar to quickly find results from multiple fieldtypes?

**Comment by jbaxleyiii** [comment]
@johnthepink thats a great idea. I can do that right now

@jonhorton `elastisearch` ❤️ ❤️ ❤️

**Comment by johnthepink** [comment]
@jonhorton @jbaxleyiii `elastisearch` ❤️ ❤️ ❤️

**Comment by jbaxleyiii** [comment]
@benwiley I think we will need to make #grouptags full text searchable so we can use `CONTAINS` here. Is that possible?

**Comment by jbaxleyiii** [comment]
@benwiley ++
