### ISSUE TITLE
Fix meta content set for Group Finder

### ISSUE THREAD

**Issue by jonhorton** [NewSpring/Apollos#813]
- Use primary #thesearemypeople image for the /groups/finder page 
- Need to add a description for the /groups/finder page
- Add fb_app_id that is used on newspring.cc 
- Images should be set for group detail pages: custom image, then fallback to default. ([Example of it not working](https://developers.facebook.com/tools/debug/sharing/?q=https%3A%2F%2Fmy.newspring.cc%2Fgroups%2Fb792f20a5cabeb76e7e98b4732732943))

❤️

**Comment by jbaxleyiii** [comment]
@jonhorton do you have a description you want me to use?

**Comment by jbaxleyiii** [comment]
also, what image do you want? Currently it uses the custom fallback per tag https://www.dropbox.com/s/t4ucyt3wqd8n03v/Screenshot%202016-07-24%2015.04.55.png?dl=0

**Comment by jbaxleyiii** [comment]
pulled text from /groups on newspring.cc
