### ISSUE TITLE
Closing OnBoarding Redirect

### ISSUE THREAD

**Issue by johnthepink** [NewSpring/Apollos#818]
Closing the OnBoarding modal while at top level navigation redirects you back to the Home feed every time.

## Steps to reproduce

1. Make sure you are signed out
2. Go to Sections
3. Go to Profile
4. Close the modal without signing in
5. You will now be at the Home Feed. This is what's wrong.

It should close the modal and take you back to the screen you are on.

This doesn't seem to happen when triggering the OnBoarding modal by being signed out and clicking a like button.

**Comment by jbaxleyiii** [comment]
@johnthepink we didn't have solution for links inside authorized sections. Those should take you home

**Comment by johnthepink** [comment]
> The reason it redirects home right now (instead of just back) is for use cases where people navigate directly to an auth space (say /profile) the modal opens, and if the close it, it needs to take them away
> 
> The key may be a hook in the authorized component to redirect there instead of the onboard component

via james
