### ISSUE TITLE
Sermon Audio

### ISSUE THREAD

**Issue by johnthepink** [NewSpring/Apollos#830]
We need to provide a way for users to play sermon audio using the music player

- [x] determine how should integrate
- [x] implement
- [x] test

**Comment by samclaridge** [comment]
@johnthepink here's the ui from within the sermon to access the audio:
background is light-primary

![screenshot 2016-08-01 16 12 25](https://cloud.githubusercontent.com/assets/7452283/17307417/0c0bd1ec-5803-11e6-8171-483343b1a9f6.png)

Here's what it looks like using the audio player.
It uses a simplified version of our music player, stripping out the secondary controls: shuffle, repeat and list detail.

![screenshot 2016-08-01 16 15 09](https://cloud.githubusercontent.com/assets/7452283/17307446/26d98d48-5803-11e6-8df1-13e5b60fd706.png)

**Comment by jbaxleyiii** [comment]
@samclaridge can you include the mini player too? These look great!

**Comment by samclaridge** [comment]
![screenshot 2016-08-01 16 44 35](https://cloud.githubusercontent.com/assets/7452283/17308306/4669513a-5807-11e6-80e4-9f796ddabd16.png)

**Comment by johnthepink** [comment]
@samclaridge @jbaxleyiii awesome thanks! Hoping to have something working today.
