### ISSUE TITLE
Music player positioning of controls, play/pause, repeat

### ISSUE THREAD

**Issue by samclaridge** [NewSpring/Apollos#834]
The play/pause buttons need to be moved to be visually centered instead of mathematically centered.

**Comment by johnthepink** [comment]
@samclaridge can you provide a screenshot of what this might look like? Thanks!

**Comment by samclaridge** [comment]
@johnthepink I think it'll be easier for me to fix this because it needs to be eye-balled.

**Comment by johnthepink** [comment]
awesome

**Comment by johnthepink** [comment]
Closed by #855
