### ISSUE TITLE
Change slide to stop Music terminology

### ISSUE THREAD

**Issue by samclaridge** [NewSpring/Apollos#862]
When listening to sermon audio if you slide to dismiss the miniplayer it should be updated to say "Stop Sermon".

Or, alternatively we update it globally to be more generic, for example "Stop Audio"

**Comment by johnthepink** [comment]
@samclaridge I'd be in favor of something more generic. At least for now. Maybe just "Stop"?

**Comment by samclaridge** [comment]
let's go with Stop Audio.
