### ISSUE TITLE
Use NickName on Giving History filters

### ISSUE THREAD

**Issue by jonhorton** [NewSpring/Apollos#866]
Currently under Giving History > Filters, the list of family members is using FirstName instead of NickName. ([Screenshot](https://www.dropbox.com/s/06a1wbhc8shw06u/Screenshot%202016-08-10%2009.01.17.png?dl=0))

Since we use NickName (if it exists) everywhere else, let's update that here for consistency!

**Comment by jbaxleyiii** [comment]
Fixed in next deploy
