### ISSUE TITLE
User campus isn't coming through since relaunch

### ISSUE THREAD

**Issue by jbaxleyiii** [NewSpring/Apollos#872]

**Comment by johnthepink** [comment]
Not sure if this is related, but I did notice when testing iOS giving that when you "Give As A Guest", the last confirm screen when giving says the word "Campus", but without an actual campus.

<img width="589" alt="screenshot 2016-09-08 14 43 18" src="https://cloud.githubusercontent.com/assets/816517/18362132/9d7cf7d6-75d2-11e6-8abd-310a042dd767.png">
