### ISSUE TITLE
Tag + Query Search in Group Finder Doesn't Respect Hidden Group Attribute

### ISSUE THREAD

**Issue by briankalwat** [NewSpring/Apollos#881]
If I go to [https://my.newspring.cc/groups/finder](url) and search `beer` it returns no results (the 3 results that are returned are hidden groups).

However, If I first click a tag such as `gaming` and then search for `beer`, it returns the results for both queries individually, instead of an advanced query that returns results that match both. It also will return ALL results that match either query, regardless of whether or not they are hidden.

**Comment by johnthepink** [comment]
Can confirm

**Comment by jbaxleyiii** [comment]
@johnthepink well we need to fix the closed group part asap

@briankalwat 

> it returns the results for both queries individually, instead of an advanced query that returns results that match both.

Currently it sorts by priority of overlap (so beer + gaming), then gaming or beer. That part is expected behavoir

**Comment by jbaxleyiii** [comment]
Fixed in next build

**Comment by jbaxleyiii** [comment]
@briankalwat thanks for the report and replication steps! 🎉
