### ISSUE TITLE
Clemson Service Times Are Wrong

### ISSUE THREAD

**Issue by richarddubay** [NewSpring/Apollos#947]
**Buggy Behavior**
When you look at the service times for the Clemson campus on the locations page, they show incorrectly. All other campuses seem to show the service times correctly. See the image.

**Expected Behavior**
The Clemson campus service times would show correctly.

![img_0782](https://cloud.githubusercontent.com/assets/3229463/18418396/729afa02-7813-11e6-9984-c378d4236522.png)

**Comment by jbaxleyiii** [comment]
@richarddubay 🎉 thanks for this!

If anyone wants to pick it up, it's a heighliner change that I can walk you through

**Comment by jbaxleyiii** [comment]
Fixed with https://github.com/NewSpring/Heighliner/pull/186
