### ISSUE TITLE
Props passed as attributes to web components

### ISSUE THREAD

**Issue by Lepozepo** [NewSpring/Apollos#95]
## Acceptance Criteria

- [ ] It should not pass props as attributes to web components
- [ ] It should not warn about it

<img width="627" alt="screen shot 2017-11-10 at 11 53 33 am" src="https://user-images.githubusercontent.com/2302110/32676039-f09f86d6-c60d-11e7-9b73-948e0867b86d.png">

**Comment by conrad-vanl** [comment]
![image](https://user-images.githubusercontent.com/103927/35939663-6e59df00-0c12-11e8-9edf-c15113290912.png)

**Comment by conrad-vanl** [comment]
I'm going to label this as a `wont-fix` for this sprint and move back into the icebox column. Unfortunately, I don't have a good solution right now other then making sure we strip out props everywhere props get accidentally passed down the chain, which is very frequent. This isn't a problem in the production version of the app, and only currently affects development work.

**Comment by conrad-vanl** [comment]
And fwiw i spent a few hours working to strip out the props and had much more work ahead of me to finish...the return doesn't seem worth it considering other more pressing issues.
